/**
 * What the two generals say during the fight.
 *
 * The defender speaks the language he spoke in the stand-off. Where that was
 * his own (a level in `STANDOFF_SUB`), every line he says in the fight is in
 * it too, with the English in a line underneath: the player reads what he
 * meant, and Buck goes on misunderstanding him, which is the same joke the
 * stand-off makes. Where it was English he goes on in English, from a longer
 * list. He used to open the fight in Egyptian Arabic and go on in English
 * the moment the first shell landed.
 *
 * The moments: a quarter of the building down, half, the airborne, the
 * counter-attack at three quarters, the last tenth, and one of the player's
 * aeroplanes brought down by his SAMs. Each draws without repeats from its
 * own list for the length of a battle, so a fight is not the same script
 * twice running.
 */
import { DEFENDER_OF } from './cast.js';
import { STANDOFF_SUB } from './subtitles.js';

/** The meanings, in English: the subtitles, and the English speakers' lines. */
const MEAN = {
  quarter: [
    'A few bricks. My grandmother loses more in a storm.',
    'You chipped it. Congratulations. We have glue.',
    'Is that the whole American army? I expected more noise.',
    'Keep shooting. The souvenir shop sells the pieces.',
  ],
  half: [
    'Half of it is still more than you will ever build.',
    'You have made my architects cry. Now I am angry.',
    'Half a monument is still a monument, cowboy.',
    'My insurance company is watching you very closely.',
  ],
  airborne: [
    'Look up, American. My paratroopers are coming.',
    'I have called my cousins. My cousins have aeroplanes.',
    'Every man I have left is in the sky. Duck.',
    'The drop zone is your head. Enjoy.',
  ],
  assault: [
    'Every man, every mortar, every missile. Now we fight.',
    'You wanted a war? Here is the whole army.',
    'My brigade lands everywhere. You have nowhere to hide.',
    'The sky is closed again, cowboy. Walk home.',
  ],
  last: [
    'Fine. FINE. It was ugly anyway.',
    'One more shot and I am changing sides.',
    'You will receive an invoice. A very long invoice.',
    'I surrender nothing! ...Except maybe the gift shop.',
  ],
  samkill: [
    'One of your aeroplanes is now a firework.',
    'Your pilot is walking home. Slowly.',
  ],
};
const ORDER = ['quarter', 'half', 'airborne', 'assault', 'last', 'samkill'];

/** More for the ones who speak English anyway: no translation to carry. */
const EN_EXTRA = {
  quarter: [
    "Is that it? I've had worse from pigeons.",
    'A scratch. My cleaners bill by the hour, you know.',
  ],
  half: [
    "Half? My grandmother could do half with a garden hose.",
    "You've made a mess. My cleaners bill by the hour.",
    'Keep going. My insurers are watching, and they are furious.',
    'Is that the best America can do? Shocking. Truly.',
  ],
  airborne: [
    'Reinforcements! Half my army again, and every one of them angry.',
    'You brought artillery. I brought the sky. Fair is fair.',
    'Gentlemen, the drop zone is the American. Go.',
  ],
  assault: [
    'That was the airborne. This is the brigade.',
    'Mortars on every street corner, and missiles to go with them. Do enjoy.',
  ],
  last: [
    "I hope you're proud. The gift shop was the best part.",
    'My mother said not to trust a man with that many howitzers.',
    'You will pay for this. Literally. There will be an invoice.',
  ],
  samkill: [
    "That was a very expensive aeroplane. Was. It was a very expensive aeroplane.",
  ],
};

/**
 * The lines, in each language, in the order of `MEAN`: four a moment and two
 * for the SAM. Keyed by language; `LANG` says who speaks which.
 */
const T = {
  fr: [
    'Quelques briques. Ma grand-mère en perd plus dans une tempête.',
    "Tu l'as ébréché. Bravo. Nous avons de la colle.",
    "C'est toute l'armée américaine ? Je m'attendais à plus de bruit.",
    'Continue. La boutique vend les morceaux en souvenir.',
    "La moitié, c'est encore plus que tout ce que tu construiras.",
    'Tu as fait pleurer mes architectes. Maintenant je suis fâché.',
    'Un demi-monument reste un monument, cow-boy.',
    'Mon assureur te regarde de très près.',
    "Lève les yeux, l'Américain. Mes parachutistes arrivent.",
    "J'ai appelé mes cousins. Mes cousins ont des avions.",
    'Tous mes hommes sont dans le ciel. Baisse la tête.',
    "La zone de largage, c'est ta tête. Bon appétit.",
    'Chaque homme, chaque mortier, chaque missile. Maintenant on se bat.',
    "Tu voulais une guerre ? Voici toute l'armée.",
    "Ma brigade tombe partout. Tu n'as nulle part où te cacher.",
    'Le ciel est de nouveau fermé, cow-boy. Rentre à pied.',
    'Bon. BON. Il était moche de toute façon.',
    'Encore un tir et je change de camp.',
    'Tu recevras une facture. Une très longue facture.',
    'Je ne cède rien ! ...Sauf peut-être la boutique de souvenirs.',
    "Un de tes avions est maintenant un feu d'artifice.",
    'Ton pilote rentre à pied. Lentement.',
  ],
  es: [
    'Unos ladrillos. Mi abuela pierde más en una tormenta.',
    'Lo has desconchado. Felicidades. Tenemos pegamento.',
    '¿Ese es todo el ejército americano? Esperaba más ruido.',
    'Sigue disparando. La tienda vende los pedazos de recuerdo.',
    'La mitad sigue siendo más de lo que tú construirás jamás.',
    'Has hecho llorar a mis arquitectos. Ahora estoy enfadado.',
    'Medio monumento sigue siendo un monumento, vaquero.',
    'Mi aseguradora te está vigilando muy de cerca.',
    'Mira arriba, americano. Mis paracaidistas ya vienen.',
    'He llamado a mis primos. Mis primos tienen aviones.',
    'Todos mis hombres están en el cielo. Agáchate.',
    'La zona de salto es tu cabeza. Que aproveche.',
    'Cada hombre, cada mortero, cada misil. Ahora sí luchamos.',
    '¿Querías una guerra? Aquí tienes el ejército entero.',
    'Mi brigada cae por todas partes. No tienes dónde esconderte.',
    'El cielo está cerrado otra vez, vaquero. Vuelve a pie.',
    'Bueno. ¡BUENO! De todos modos era feo.',
    'Un disparo más y me cambio de bando.',
    'Recibirás una factura. Una factura muy larga.',
    '¡No me rindo! ...Salvo quizá la tienda de recuerdos.',
    'Uno de tus aviones ahora es un fuego artificial.',
    'Tu piloto vuelve a casa andando. Despacio.',
  ],
  pt: [
    'Uns tijolos. A minha avó perde mais numa tempestade.',
    'Lascaste-o. Parabéns. Temos cola.',
    'Este é o exército americano inteiro? Esperava mais barulho.',
    'Continua a disparar. A loja vende os pedaços como lembrança.',
    'Metade ainda é mais do que alguma vez vais construir.',
    'Fizeste chorar os meus arquitetos. Agora estou zangado.',
    'Meio monumento continua a ser um monumento, cowboy.',
    'A minha seguradora está a observar-te muito de perto.',
    'Olha para cima, americano. Os meus paraquedistas vêm aí.',
    'Chamei os meus primos. Os meus primos têm aviões.',
    'Todos os meus homens estão no céu. Abaixa-te.',
    'A zona de salto é a tua cabeça. Bom proveito.',
    'Cada homem, cada morteiro, cada míssil. Agora sim, lutamos.',
    'Querias uma guerra? Aqui está o exército inteiro.',
    'A minha brigada cai em todo o lado. Não tens onde te esconder.',
    'O céu está fechado outra vez, cowboy. Volta a pé.',
    'Pronto. PRONTO. Era feio de qualquer maneira.',
    'Mais um tiro e mudo de lado.',
    'Vais receber uma fatura. Uma fatura muito longa.',
    'Não entrego nada! ...Exceto talvez a loja de lembranças.',
    'Um dos teus aviões é agora fogo de artifício.',
    'O teu piloto volta a pé. Devagar.',
  ],
  it: [
    'Qualche mattone. Mia nonna ne perde di più in un temporale.',
    "L'hai scheggiato. Complimenti. Abbiamo la colla.",
    "Questo è tutto l'esercito americano? Mi aspettavo più rumore.",
    'Continua a sparare. Il negozio vende i pezzi come souvenir.',
    'Metà è ancora più di quanto tu costruirai mai.',
    'Hai fatto piangere i miei architetti. Adesso sono arrabbiato.',
    'Mezzo monumento è sempre un monumento, cowboy.',
    'La mia assicurazione ti sta guardando molto da vicino.',
    'Guarda in alto, americano. Arrivano i miei paracadutisti.',
    'Ho chiamato i miei cugini. I miei cugini hanno gli aerei.',
    'Tutti i miei uomini sono in cielo. Abbassati.',
    'La zona di lancio è la tua testa. Buon appetito.',
    'Ogni uomo, ogni mortaio, ogni missile. Adesso si combatte.',
    "Volevi una guerra? Ecco l'esercito intero.",
    'La mia brigata scende ovunque. Non hai dove nasconderti.',
    'Il cielo è di nuovo chiuso, cowboy. Torna a piedi.',
    'Va bene. VA BENE. Era brutto comunque.',
    'Ancora un colpo e cambio bandiera.',
    'Riceverai una fattura. Una fattura lunghissima.',
    'Non cedo niente! ...Tranne forse il negozio di souvenir.',
    "Uno dei tuoi aerei adesso è un fuoco d'artificio.",
    'Il tuo pilota torna a casa a piedi. Piano piano.',
  ],
  de: [
    'Ein paar Ziegel. Meine Oma verliert mehr bei einem Sturm.',
    'Du hast es angekratzt. Glückwunsch. Wir haben Kleber.',
    'Ist das die ganze amerikanische Armee? Ich hatte mehr Lärm erwartet.',
    'Schieß weiter. Der Laden verkauft die Stücke als Andenken.',
    'Die Hälfte ist immer noch mehr, als du je bauen wirst.',
    'Du hast meine Architekten zum Weinen gebracht. Jetzt bin ich wütend.',
    'Ein halbes Denkmal ist immer noch ein Denkmal, Cowboy.',
    'Meine Versicherung beobachtet dich sehr genau.',
    'Schau nach oben, Amerikaner. Meine Fallschirmjäger kommen.',
    'Ich habe meine Cousins angerufen. Meine Cousins haben Flugzeuge.',
    'Alle meine Männer sind in der Luft. Kopf runter.',
    'Die Absprungzone ist dein Kopf. Guten Appetit.',
    'Jeder Mann, jeder Mörser, jede Rakete. Jetzt wird gekämpft.',
    'Du wolltest Krieg? Hier ist die ganze Armee.',
    'Meine Brigade landet überall. Du kannst dich nirgends verstecken.',
    'Der Himmel ist wieder zu, Cowboy. Geh zu Fuß nach Hause.',
    'Schön. SCHÖN. Es war sowieso hässlich.',
    'Noch ein Schuss und ich laufe über.',
    'Du bekommst eine Rechnung. Eine sehr lange Rechnung.',
    'Ich gebe nichts auf! ...Außer vielleicht den Souvenirladen.',
    'Eines deiner Flugzeuge ist jetzt ein Feuerwerk.',
    'Dein Pilot geht zu Fuß nach Hause. Langsam.',
  ],
  ru: [
    'Пара кирпичей. Моя бабушка теряет больше в бурю.',
    'Ты его поцарапал. Поздравляю. У нас есть клей.',
    'Это вся американская армия? Я ждал больше шума.',
    'Стреляй дальше. Сувенирная лавка продаёт осколки.',
    'Половина — это всё ещё больше, чем ты когда-нибудь построишь.',
    'Мои архитекторы плачут. Теперь я зол.',
    'Полпамятника — всё равно памятник, ковбой.',
    'Моя страховая компания очень внимательно за тобой следит.',
    'Посмотри наверх, американец. Мои десантники уже летят.',
    'Я позвонил кузенам. У моих кузенов есть самолёты.',
    'Все мои люди в небе. Пригнись.',
    'Зона высадки — твоя голова. Приятного аппетита.',
    'Каждый солдат, каждый миномёт, каждая ракета. Теперь воюем.',
    'Хотел войну? Вот тебе вся армия.',
    'Моя бригада садится везде. Тебе негде спрятаться.',
    'Небо снова закрыто, ковбой. Иди домой пешком.',
    'Ладно. ЛАДНО. Всё равно было некрасиво.',
    'Ещё один выстрел — и я перехожу на другую сторону.',
    'Ты получишь счёт. Очень длинный счёт.',
    'Я ничего не сдам! ...Кроме, может быть, сувенирной лавки.',
    'Один из твоих самолётов теперь салют.',
    'Твой пилот идёт домой пешком. Медленно.',
  ],
  kk: [
    'Бірнеше кірпіш. Әжем дауылда бұдан көп жоғалтады.',
    'Сен оны сызаттадың. Құттықтаймын. Бізде желім бар.',
    'Американ әскері осы ма? Мен көбірек шу күттім.',
    'Ата бер. Дүкен сынықтарын кәдесый ретінде сатады.',
    'Жартысы да сенің бүкіл салғаныңнан көп.',
    'Сәулетшілерімді жылаттың. Енді мен ашулымын.',
    'Жарты ескерткіш те ескерткіш, ковбой.',
    'Сақтандыру компаниям сені қатты бақылап отыр.',
    'Жоғары қара, американ. Десантшыларым келе жатыр.',
    'Туыстарымды шақырдым. Туыстарымның ұшақтары бар.',
    'Барлық адамым аспанда. Еңкей.',
    'Түсу аймағы — сенің басың. Ас болсын.',
    'Әр сарбаз, әр миномет, әр зымыран. Енді соғысамыз.',
    'Соғыс керек пе еді? Міне, бүкіл әскер.',
    'Бригадам барлық жерге түседі. Сен жасырына алмайсың.',
    'Аспан қайта жабық, ковбой. Үйіңе жаяу қайт.',
    'Жарайды. ЖАРАЙДЫ. Бәрібір әдемі емес еді.',
    'Тағы бір оқ, мен жағымды ауыстырамын.',
    'Саған шот келеді. Өте ұзын шот.',
    'Ештеңе бермеймін! ...Кәдесый дүкенінен басқа.',
    'Ұшақтарыңның бірі енді отшашу.',
    'Ұшқышың үйіне жаяу кетіп барады. Ақырын.',
  ],
  ar: [
    'بضع طوبات. جدتي تخسر أكثر من هذا في عاصفة.',
    'خدشته. مبروك. عندنا غراء.',
    'هذا كل الجيش الأمريكي؟ توقعت ضجيجاً أكثر.',
    'استمر في الإطلاق. محل الهدايا يبيع القطع للسياح.',
    'النصف ما زال أكثر من كل ما ستبنيه في حياتك.',
    'أبكيت مهندسيّ المعماريين. الآن أنا غاضب.',
    'نصف نصب تذكاري يبقى نصباً تذكارياً يا كاوبوي.',
    'شركة التأمين تراقبك عن قرب شديد.',
    'انظر إلى الأعلى يا أمريكي. مظلّيّيّ قادمون.',
    'اتصلت بأبناء عمي. أبناء عمي عندهم طائرات.',
    'كل رجالي في السماء. انحنِ.',
    'منطقة الإنزال هي رأسك. بالهناء والشفاء.',
    'كل رجل، كل هاون، كل صاروخ. الآن نقاتل.',
    'أردت حرباً؟ هذا هو الجيش كله.',
    'لوائي ينزل في كل مكان. لا مكان تختبئ فيه.',
    'السماء مغلقة من جديد يا كاوبوي. ارجع ماشياً.',
    'حسناً. حسناً! كان قبيحاً على أي حال.',
    'طلقة واحدة أخرى وأنتقل إلى الجانب الآخر.',
    'ستصلك فاتورة. فاتورة طويلة جداً.',
    'لن أتنازل عن شيء! ...إلا ربما محل الهدايا.',
    'إحدى طائراتك صارت ألعاباً نارية.',
    'طيارك يعود إلى بيته ماشياً. ببطء.',
  ],
  el: [
    'Λίγα τούβλα. Η γιαγιά μου χάνει περισσότερα σε μια καταιγίδα.',
    'Το γρατσούνισες. Συγχαρητήρια. Έχουμε κόλλα.',
    'Αυτός είναι όλος ο αμερικανικός στρατός; Περίμενα περισσότερο θόρυβο.',
    'Συνέχισε να ρίχνεις. Το μαγαζί πουλάει τα κομμάτια για σουβενίρ.',
    'Το μισό είναι ακόμα περισσότερο απ\' όσα θα χτίσεις ποτέ.',
    'Έκανες τους αρχιτέκτονές μου να κλάψουν. Τώρα θύμωσα.',
    'Μισό μνημείο είναι πάλι μνημείο, καουμπόη.',
    'Η ασφαλιστική μου σε παρακολουθεί πολύ στενά.',
    'Κοίτα ψηλά, Αμερικάνε. Έρχονται οι αλεξιπτωτιστές μου.',
    'Πήρα τηλέφωνο τα ξαδέρφια μου. Τα ξαδέρφια μου έχουν αεροπλάνα.',
    'Όλοι οι άντρες μου είναι στον ουρανό. Σκύψε.',
    'Η ζώνη ρίψης είναι το κεφάλι σου. Καλή όρεξη.',
    'Κάθε άντρας, κάθε όλμος, κάθε πύραυλος. Τώρα πολεμάμε.',
    'Ήθελες πόλεμο; Ορίστε όλος ο στρατός.',
    'Η ταξιαρχία μου πέφτει παντού. Δεν έχεις πού να κρυφτείς.',
    'Ο ουρανός έκλεισε πάλι, καουμπόη. Γύρνα με τα πόδια.',
    'Καλά. ΚΑΛΑ. Έτσι κι αλλιώς ήταν άσχημο.',
    'Μία βολή ακόμα και αλλάζω στρατόπεδο.',
    'Θα σου έρθει λογαριασμός. Πολύ μακρύς λογαριασμός.',
    'Δεν παραδίδω τίποτα! ...Εκτός ίσως από το μαγαζί με τα σουβενίρ.',
    'Ένα από τα αεροπλάνα σου είναι τώρα πυροτέχνημα.',
    'Ο πιλότος σου γυρίζει σπίτι με τα πόδια. Σιγά σιγά.',
  ],
  tr: [
    'Birkaç tuğla. Babaannem fırtınada bundan fazlasını kaybeder.',
    'Çizdin. Tebrikler. Yapıştırıcımız var.',
    'Bütün Amerikan ordusu bu mu? Daha çok gürültü bekliyordum.',
    'Ateş etmeye devam et. Hediyelik eşya dükkânı parçaları satıyor.',
    'Yarısı bile senin hayatın boyunca yapacağından fazla.',
    'Mimarlarımı ağlattın. Şimdi sinirlendim.',
    'Yarım anıt yine de anıttır, kovboy.',
    'Sigorta şirketim seni çok yakından izliyor.',
    'Yukarı bak, Amerikalı. Paraşütçülerim geliyor.',
    'Kuzenlerimi aradım. Kuzenlerimin uçakları var.',
    'Bütün adamlarım gökyüzünde. Eğil.',
    'İniş bölgesi senin kafan. Afiyet olsun.',
    'Her asker, her havan, her füze. Şimdi savaşıyoruz.',
    'Savaş mı istedin? İşte bütün ordu.',
    'Tugayım her yere iniyor. Saklanacak yerin yok.',
    'Gökyüzü yine kapandı, kovboy. Eve yürüyerek dön.',
    'Peki. PEKİ. Zaten çirkindi.',
    'Bir atış daha ve taraf değiştiriyorum.',
    'Sana bir fatura gelecek. Çok uzun bir fatura.',
    'Hiçbir şey teslim etmem! ...Belki hediyelik eşya dükkânı hariç.',
    'Uçaklarından biri artık havai fişek.',
    'Pilotun eve yürüyerek dönüyor. Yavaş yavaş.',
  ],
  ja: [
    'レンガが少し。うちのばあちゃんは嵐でもっと失くすぞ。',
    '欠けただけだ。おめでとう。接着剤ならある。',
    'それがアメリカ軍の全部か？もっとうるさいと思っていた。',
    '撃ち続けろ。土産物屋がかけらを売っている。',
    '半分でも、お前が一生で建てるものより多い。',
    '建築家たちが泣いている。今、俺は怒っている。',
    '半分の記念碑でも記念碑だ、カウボーイ。',
    '保険会社がお前をじっと見ているぞ。',
    '上を見ろ、アメリカ人。空挺部隊が来るぞ。',
    'いとこたちを呼んだ。いとこたちは飛行機を持っている。',
    '残りの兵は全員空の上だ。頭を下げろ。',
    '降下地点はお前の頭だ。召し上がれ。',
    '兵も迫撃砲もミサイルも全部だ。さあ戦おう。',
    '戦争がしたかったのか？これが全軍だ。',
    '我が旅団はどこにでも降りる。隠れる場所はない。',
    '空はまた閉じた、カウボーイ。歩いて帰れ。',
    'いいだろう。いいだろう！どうせ醜かったんだ。',
    'あと一発撃ったら、寝返るぞ。',
    '請求書が届くぞ。とても長い請求書がな。',
    '何も渡さん！…土産物屋くらいは別だが。',
    'お前の飛行機が一機、花火になったぞ。',
    'お前のパイロットは歩いて帰るところだ。ゆっくりとな。',
  ],
  zh: [
    '几块砖而已。我奶奶在一场暴风里丢的都比这多。',
    '你磕掉了一点。恭喜。我们有胶水。',
    '这就是整个美军？我以为会更吵一点。',
    '接着打。纪念品商店正在卖碎片。',
    '剩下的一半，也比你这辈子盖的多。',
    '你把我的建筑师都弄哭了。现在我生气了。',
    '半座纪念碑也还是纪念碑，牛仔。',
    '我的保险公司正盯着你呢。',
    '抬头看，美国人。我的伞兵来了。',
    '我叫了我的表兄弟。我的表兄弟有飞机。',
    '我剩下的人全在天上。低头。',
    '空降区就是你的脑袋。请慢用。',
    '每个兵，每门迫击炮，每枚导弹。现在才是真打。',
    '你想要战争？整支军队都来了。',
    '我的旅到处都在降落。你无处可藏。',
    '天空又封锁了，牛仔。走回家吧。',
    '好吧。好吧！反正它本来就很丑。',
    '再来一炮，我就投降到你那边去。',
    '你会收到一张账单。很长很长的账单。',
    '我什么都不交！……也许纪念品商店除外。',
    '你的一架飞机现在成了烟花。',
    '你的飞行员正在走路回家。慢慢走。',
  ],
  'zh-tw': [
    '幾塊磚而已。我阿嬤在一場颱風裡丟的都比這多。',
    '你敲掉了一點。恭喜。我們有膠水。',
    '這就是整個美軍？我以為會更吵一點。',
    '繼續打。紀念品店正在賣碎片。',
    '剩下的一半，也比你這輩子蓋的多。',
    '你把我的建築師都弄哭了。現在我生氣了。',
    '半座紀念碑也還是紀念碑，牛仔。',
    '我的保險公司正盯著你呢。',
    '抬頭看，美國人。我的傘兵來了。',
    '我叫了我的表兄弟。我的表兄弟有飛機。',
    '我剩下的人全在天上。低頭。',
    '空降區就是你的腦袋。請慢用。',
    '每個兵，每門迫擊砲，每枚飛彈。現在才是真打。',
    '你想要戰爭？整支軍隊都來了。',
    '我的旅到處都在降落。你無處可藏。',
    '天空又封鎖了，牛仔。走路回家吧。',
    '好吧。好吧！反正它本來就很醜。',
    '再來一砲，我就投靠你那邊。',
    '你會收到一張帳單。很長很長的帳單。',
    '我什麼都不交！……也許紀念品店除外。',
    '你的一架飛機現在成了煙火。',
    '你的飛行員正走路回家。慢慢走。',
  ],
  ko: [
    '벽돌 몇 장이군. 우리 할머니는 태풍에 더 많이 잃소.',
    '흠집 하나 냈군. 축하하오. 우리에겐 접착제가 있소.',
    '이게 미군 전부요? 더 시끄러울 줄 알았는데.',
    '계속 쏘시오. 기념품 가게가 조각을 팔고 있소.',
    '남은 절반도 당신이 평생 지을 것보다 많소.',
    '건축가들이 울고 있소. 이제 나는 화가 났소.',
    '반쪽짜리 기념물도 기념물이오, 카우보이.',
    '우리 보험회사가 당신을 아주 가까이서 지켜보고 있소.',
    '위를 보시오, 미국인. 내 공수부대가 오고 있소.',
    '사촌들을 불렀소. 내 사촌들은 비행기가 있소.',
    '남은 병사는 모두 하늘에 있소. 고개 숙이시오.',
    '강하 지점은 당신 머리요. 맛있게 드시오.',
    '모든 병사, 모든 박격포, 모든 미사일. 이제 진짜 싸움이오.',
    '전쟁을 원했소? 여기 군대 전체가 왔소.',
    '내 여단이 사방에 내리고 있소. 숨을 곳은 없소.',
    '하늘은 다시 닫혔소, 카우보이. 걸어서 돌아가시오.',
    '좋소. 좋소! 어차피 못생겼었소.',
    '한 발만 더 쏘면 나는 편을 바꾸겠소.',
    '청구서가 갈 것이오. 아주 긴 청구서가.',
    '아무것도 내주지 않겠소! ...기념품 가게라면 몰라도.',
    '당신 비행기 한 대가 이제 불꽃놀이가 되었소.',
    '당신 조종사는 걸어서 집에 가고 있소. 천천히.',
  ],
  th: [
    'อิฐไม่กี่ก้อน ยายผมเสียมากกว่านี้ตอนพายุเข้า',
    'แค่บิ่นนิดหน่อย ยินดีด้วย เรามีกาว',
    'นี่คือกองทัพอเมริกันทั้งหมดเหรอ นึกว่าจะเสียงดังกว่านี้',
    'ยิงต่อไปเถอะ ร้านของที่ระลึกกำลังขายเศษอยู่',
    'ครึ่งเดียวก็ยังมากกว่าที่คุณจะสร้างได้ทั้งชีวิต',
    'คุณทำให้สถาปนิกของผมร้องไห้ ตอนนี้ผมโกรธแล้ว',
    'อนุสรณ์ครึ่งเดียวก็ยังเป็นอนุสรณ์ คาวบอย',
    'บริษัทประกันของผมจับตาดูคุณอย่างใกล้ชิด',
    'มองขึ้นไปสิ คนอเมริกัน ทหารพลร่มของผมมาแล้ว',
    'ผมโทรเรียกลูกพี่ลูกน้องแล้ว พวกเขามีเครื่องบิน',
    'ทหารที่เหลือทุกคนอยู่บนฟ้า ก้มหัวลง',
    'จุดกระโดดคือหัวของคุณ เชิญตามสบาย',
    'ทหารทุกคน ปืนครกทุกกระบอก ขีปนาวุธทุกลูก ตอนนี้สู้กันจริงแล้ว',
    'อยากได้สงครามใช่ไหม นี่คือกองทัพทั้งหมด',
    'กองพลน้อยของผมลงทุกที่ คุณไม่มีที่ซ่อน',
    'ท้องฟ้าปิดอีกแล้ว คาวบอย เดินกลับบ้านไปเถอะ',
    'ก็ได้ ก็ได้! ยังไงมันก็น่าเกลียดอยู่แล้ว',
    'ยิงอีกนัดเดียว ผมจะย้ายข้าง',
    'คุณจะได้รับใบแจ้งหนี้ ใบแจ้งหนี้ที่ยาวมาก',
    'ผมไม่ยอมให้อะไรทั้งนั้น! ...ยกเว้นร้านของที่ระลึก',
    'เครื่องบินของคุณลำหนึ่งกลายเป็นดอกไม้ไฟไปแล้ว',
    'นักบินของคุณกำลังเดินกลับบ้าน ช้าๆ',
  ],
  my: [
    'အုတ်ခဲ အနည်းငယ်ပဲ။ ကျွန်တော့်အဖွားက မုန်တိုင်းထဲမှာ ဒီထက်ပိုဆုံးရှုံးတယ်။',
    'နည်းနည်းပဲ ပဲ့သွားတယ်။ ဂုဏ်ယူပါတယ်။ ကျွန်တော်တို့မှာ ကော်ရှိတယ်။',
    'ဒါ အမေရိကန်စစ်တပ် တစ်ခုလုံးလား။ ပိုဆူညံမယ်ထင်ခဲ့တာ။',
    'ဆက်ပစ်ပါ။ အမှတ်တရဆိုင်က အပိုင်းအစတွေကို ရောင်းနေတယ်။',
    'တစ်ဝက်တောင် ခင်ဗျားတစ်သက်လုံး ဆောက်မယ့်ဟာထက် များသေးတယ်။',
    'ကျွန်တော့် ဗိသုကာတွေ ငိုနေကြပြီ။ အခု ကျွန်တော် စိတ်ဆိုးပြီ။',
    'တစ်ဝက်ပဲကျန်တဲ့ အထိမ်းအမှတ်လည်း အထိမ်းအမှတ်ပါပဲ၊ ကောင်းဘွိုင်။',
    'ကျွန်တော့် အာမခံကုမ္ပဏီက ခင်ဗျားကို အနီးကပ်စောင့်ကြည့်နေတယ်။',
    'အပေါ်ကိုကြည့်၊ အမေရိကန်။ ကျွန်တော့် လေထီးတပ်တွေ လာနေပြီ။',
    'ဝမ်းကွဲတွေကို ခေါ်လိုက်ပြီ။ သူတို့မှာ လေယာဉ်တွေရှိတယ်။',
    'ကျန်တဲ့ လူအားလုံး ကောင်းကင်ထဲမှာ။ ခေါင်းငုံ့ထား။',
    'ဆင်းမယ့်နေရာက ခင်ဗျားခေါင်းပဲ။ သုံးဆောင်ပါ။',
    'စစ်သားတိုင်း၊ မော်တာတိုင်း၊ ဒုံးကျည်တိုင်း။ အခုမှ တကယ်တိုက်မယ်။',
    'စစ်ပွဲလိုချင်တာလား။ ဒီမှာ စစ်တပ်တစ်ခုလုံးပဲ။',
    'ကျွန်တော့်တပ်မဟာ နေရာတိုင်းဆင်းနေတယ်။ ပုန်းစရာနေရာမရှိဘူး။',
    'ကောင်းကင် ပြန်ပိတ်သွားပြီ၊ ကောင်းဘွိုင်။ လမ်းလျှောက်ပြီးပြန်။',
    'ကောင်းပြီ။ ကောင်းပြီ! ဘယ်လိုပဲဖြစ်ဖြစ် ရုပ်ဆိုးနေတာပဲ။',
    'နောက်တစ်ချက်ပစ်ရင် ကျွန်တော် ဘက်ပြောင်းမယ်။',
    'ခင်ဗျားဆီ ငွေတောင်းခံလွှာ ရောက်လာမယ်။ အရမ်းရှည်တဲ့ တစ်စောင်။',
    'ဘာမှ မပေးဘူး! ...အမှတ်တရဆိုင်ကလွဲရင်ပေါ့။',
    'ခင်ဗျားရဲ့ လေယာဉ်တစ်စင်း အခု မီးပန်းဖြစ်သွားပြီ။',
    'ခင်ဗျားရဲ့ လေယာဉ်မှူး လမ်းလျှောက်ပြီး အိမ်ပြန်နေတယ်။ ဖြည်းဖြည်း။',
  ],
  km: [
    'ឥដ្ឋពីរបីដុំប៉ុណ្ណោះ។ យាយខ្ញុំបាត់ច្រើនជាងនេះពេលមានព្យុះ។',
    'អ្នកធ្វើឲ្យវាប្រេះបន្តិច។ អបអរសាទរ។ យើងមានកាវ។',
    'នេះជាកងទ័ពអាមេរិកទាំងមូលឬ? ខ្ញុំគិតថាវានឹងឮខ្លាំងជាងនេះ។',
    'បាញ់បន្តទៅ។ ហាងវត្ថុអនុស្សាវរីយ៍កំពុងលក់បំណែករបស់វា។',
    'ពាក់កណ្ដាលក៏នៅច្រើនជាងអ្វីដែលអ្នកនឹងសាងសង់ពេញមួយជីវិត។',
    'អ្នកធ្វើឲ្យស្ថាបត្យកររបស់ខ្ញុំយំ។ ឥឡូវខ្ញុំខឹងហើយ។',
    'វិមានពាក់កណ្ដាលក៏នៅតែជាវិមាន ខោប៊យ។',
    'ក្រុមហ៊ុនធានារ៉ាប់រងរបស់ខ្ញុំកំពុងតាមដានអ្នកយ៉ាងជិត។',
    'មើលទៅលើ អាមេរិក។ ទាហានឆ័ត្រយោងរបស់ខ្ញុំកំពុងមក។',
    'ខ្ញុំបានហៅបងប្អូនជីដូនមួយ។ ពួកគេមានយន្តហោះ។',
    'ទាហានដែលនៅសល់ទាំងអស់នៅលើមេឃ។ ឱនក្បាលទៅ។',
    'តំបន់ចុះគឺក្បាលរបស់អ្នក។ សូមអញ្ជើញ។',
    'ទាហានគ្រប់រូប កាំភ្លើងត្បាល់គ្រប់ដើម មីស៊ីលគ្រប់គ្រាប់។ ឥឡូវយើងប្រយុទ្ធពិតប្រាកដ។',
    'ចង់បានសង្គ្រាមមែនទេ? នេះគឺកងទ័ពទាំងមូល។',
    'កងពលតូចរបស់ខ្ញុំចុះគ្រប់ទីកន្លែង។ អ្នកគ្មានកន្លែងលាក់ខ្លួនទេ។',
    'មេឃបិទម្ដងទៀតហើយ ខោប៊យ។ ដើរត្រឡប់ទៅផ្ទះវិញទៅ។',
    'បានហើយ។ បានហើយ! វាអាក្រក់មើលទៅហើយ។',
    'បាញ់មួយគ្រាប់ទៀត ខ្ញុំនឹងប្ដូរខាង។',
    'អ្នកនឹងទទួលបានវិក្កយបត្រ។ វិក្កយបត្រវែងណាស់។',
    'ខ្ញុំមិនប្រគល់អ្វីទេ! ...លើកលែងតែហាងវត្ថុអនុស្សាវរីយ៍។',
    'យន្តហោះមួយគ្រឿងរបស់អ្នក ឥឡូវក្លាយជាកាំជ្រួចហើយ។',
    'អ្នកបើកយន្តហោះរបស់អ្នកកំពុងដើរទៅផ្ទះ។ យឺតៗ។',
  ],
  id: [
    'Cuma beberapa bata. Nenekku kehilangan lebih banyak waktu badai.',
    'Kau cuma membuatnya gompal. Selamat. Kami punya lem.',
    'Itu seluruh tentara Amerika? Kukira lebih berisik.',
    'Terus tembak. Toko suvenir menjual pecahannya.',
    'Separuhnya pun masih lebih dari yang akan kau bangun seumur hidup.',
    'Kau membuat arsitekku menangis. Sekarang aku marah.',
    'Setengah monumen tetap monumen, koboi.',
    'Perusahaan asuransiku mengawasimu dengan sangat teliti.',
    'Lihat ke atas, orang Amerika. Pasukan payungku datang.',
    'Aku sudah memanggil sepupu-sepupuku. Mereka punya pesawat.',
    'Semua anak buahku ada di langit. Menunduk.',
    'Zona pendaratannya kepalamu. Selamat menikmati.',
    'Setiap prajurit, setiap mortir, setiap rudal. Sekarang kita bertempur.',
    'Kau mau perang? Ini seluruh tentaraku.',
    'Brigadeku mendarat di mana-mana. Kau tak punya tempat bersembunyi.',
    'Langit tertutup lagi, koboi. Pulanglah jalan kaki.',
    'Baik. BAIK! Lagi pula bangunan itu jelek.',
    'Satu tembakan lagi dan aku pindah pihak.',
    'Kau akan menerima tagihan. Tagihan yang sangat panjang.',
    'Aku tak menyerahkan apa pun! ...Kecuali mungkin toko suvenir.',
    'Salah satu pesawatmu sekarang jadi kembang api.',
    'Pilotmu pulang jalan kaki. Pelan-pelan.',
  ],
  ms: [
    'Cuma beberapa bata. Nenek saya hilang lebih banyak masa ribut.',
    'Awak cuma sumbingkannya. Tahniah. Kami ada gam.',
    'Itu seluruh tentera Amerika? Saya sangka lebih bising.',
    'Teruskan menembak. Kedai cenderamata menjual serpihannya.',
    'Separuh pun masih lebih daripada apa yang awak akan bina seumur hidup.',
    'Awak buat arkitek saya menangis. Sekarang saya marah.',
    'Separuh monumen tetap monumen, koboi.',
    'Syarikat insurans saya sedang memerhati awak dengan teliti.',
    'Pandang ke atas, orang Amerika. Askar payung saya sedang datang.',
    'Saya sudah panggil sepupu saya. Mereka ada kapal terbang.',
    'Semua orang saya ada di langit. Tunduk.',
    'Zon pendaratan ialah kepala awak. Selamat menjamu selera.',
    'Setiap askar, setiap mortar, setiap peluru berpandu. Sekarang kita berperang.',
    'Awak mahu perang? Inilah seluruh tentera.',
    'Briged saya mendarat di mana-mana. Awak tiada tempat bersembunyi.',
    'Langit tertutup semula, koboi. Balik jalan kaki.',
    'Baiklah. BAIKLAH! Lagipun ia hodoh.',
    'Satu tembakan lagi dan saya tukar pihak.',
    'Awak akan terima bil. Bil yang sangat panjang.',
    'Saya tak serahkan apa-apa! ...Kecuali mungkin kedai cenderamata.',
    'Salah satu kapal terbang awak sekarang jadi bunga api.',
    'Juruterbang awak balik jalan kaki. Perlahan-lahan.',
  ],
  hu: [
    'Néhány tégla. A nagymamám többet veszít egy viharban.',
    'Megkarcoltad. Gratulálok. Van ragasztónk.',
    'Ez az egész amerikai hadsereg? Több zajra számítottam.',
    'Lőj csak tovább. Az ajándékbolt árulja a darabokat.',
    'A fele is több, mint amit te valaha építeni fogsz.',
    'Megríkattad az építészeimet. Most már dühös vagyok.',
    'Egy fél emlékmű is emlékmű, cowboy.',
    'A biztosítóm nagyon közelről figyel téged.',
    'Nézz fel, amerikai. Jönnek az ejtőernyőseim.',
    'Felhívtam az unokatestvéreimet. Nekik repülőik vannak.',
    'Minden emberem az égen van. Hajolj le.',
    'A ledobási zóna a fejed. Jó étvágyat.',
    'Minden ember, minden aknavető, minden rakéta. Most harcolunk.',
    'Háborút akartál? Itt az egész hadsereg.',
    'A dandárom mindenhol landol. Nincs hová bújnod.',
    'Az ég megint zárva, cowboy. Gyalog mész haza.',
    'Jól van. JÓL VAN! Amúgy is csúnya volt.',
    'Még egy lövés, és átállok.',
    'Kapsz egy számlát. Egy nagyon hosszú számlát.',
    'Semmit sem adok fel! ...Kivéve talán az ajándékboltot.',
    'Az egyik repülőd most tűzijáték.',
    'A pilótád gyalog megy haza. Lassan.',
  ],
  cs: [
    'Pár cihel. Moje babička ztratí víc při bouřce.',
    'Odštípl jsi kousek. Gratuluju. Máme lepidlo.',
    'To je celá americká armáda? Čekal jsem víc hluku.',
    'Střílej dál. Obchod se suvenýry prodává úlomky.',
    'I polovina je víc, než kdy postavíš ty.',
    'Rozplakal jsi mé architekty. Teď jsem naštvaný.',
    'Půlka památky je pořád památka, kovboji.',
    'Moje pojišťovna tě velmi pozorně sleduje.',
    'Podívej se nahoru, Američane. Moji výsadkáři přicházejí.',
    'Zavolal jsem bratrance. Moji bratranci mají letadla.',
    'Všichni moji muži jsou ve vzduchu. Skloň hlavu.',
    'Zóna seskoku je tvoje hlava. Dobrou chuť.',
    'Každý muž, každý minomet, každá raketa. Teď se bojuje.',
    'Chtěl jsi válku? Tady je celá armáda.',
    'Moje brigáda přistává všude. Nemáš se kam schovat.',
    'Nebe je zase zavřené, kovboji. Jdi domů pěšky.',
    'Dobře. DOBŘE! Stejně to bylo ošklivé.',
    'Ještě jeden výstřel a přejdu na druhou stranu.',
    'Dostaneš fakturu. Hodně dlouhou fakturu.',
    'Nic nevzdám! ...Snad kromě obchodu se suvenýry.',
    'Jedno z tvých letadel je teď ohňostroj.',
    'Tvůj pilot jde domů pěšky. Pomalu.',
  ],
  pl: [
    'Kilka cegieł. Moja babcia traci więcej podczas burzy.',
    'Wyszczerbiłeś go. Gratulacje. Mamy klej.',
    'To cała armia amerykańska? Spodziewałem się więcej hałasu.',
    'Strzelaj dalej. Sklep z pamiątkami sprzedaje kawałki.',
    'Połowa to wciąż więcej, niż ty kiedykolwiek zbudujesz.',
    'Doprowadziłeś moich architektów do płaczu. Teraz jestem zły.',
    'Pół pomnika to wciąż pomnik, kowboju.',
    'Mój ubezpieczyciel bardzo uważnie cię obserwuje.',
    'Spójrz w górę, Amerykaninie. Nadlatują moi spadochroniarze.',
    'Zadzwoniłem do kuzynów. Moi kuzyni mają samoloty.',
    'Wszyscy moi ludzie są w powietrzu. Schyl się.',
    'Strefa zrzutu to twoja głowa. Smacznego.',
    'Każdy żołnierz, każdy moździerz, każda rakieta. Teraz walczymy.',
    'Chciałeś wojny? Oto cała armia.',
    'Moja brygada ląduje wszędzie. Nie masz się gdzie ukryć.',
    'Niebo znów zamknięte, kowboju. Wracaj pieszo.',
    'Dobrze. DOBRZE! I tak był brzydki.',
    'Jeszcze jeden strzał i przechodzę na drugą stronę.',
    'Dostaniesz rachunek. Bardzo długi rachunek.',
    'Niczego nie oddam! ...Może poza sklepem z pamiątkami.',
    'Jeden z twoich samolotów to teraz fajerwerk.',
    'Twój pilot wraca do domu pieszo. Powoli.',
  ],
  ro: [
    'Câteva cărămizi. Bunica mea pierde mai mult într-o furtună.',
    'L-ai ciobit. Felicitări. Avem lipici.',
    'Asta e toată armata americană? Mă așteptam la mai mult zgomot.',
    'Trage în continuare. Magazinul de suveniruri vinde bucățile.',
    'Jumătate e tot mai mult decât vei construi tu vreodată.',
    'Mi-ai făcut arhitecții să plângă. Acum sunt furios.',
    'Jumătate de monument tot monument e, cowboy.',
    'Asigurătorul meu te urmărește foarte atent.',
    'Uită-te în sus, americanule. Vin parașutiștii mei.',
    'I-am chemat pe verii mei. Verii mei au avioane.',
    'Toți oamenii mei sunt în aer. Apleacă-te.',
    'Zona de aterizare e capul tău. Poftă bună.',
    'Fiecare om, fiecare mortier, fiecare rachetă. Acum ne luptăm.',
    'Voiai război? Iată toată armata.',
    'Brigada mea aterizează peste tot. N-ai unde să te ascunzi.',
    'Cerul e din nou închis, cowboy. Mergi acasă pe jos.',
    'Bine. BINE! Oricum era urât.',
    'Încă o lovitură și trec de partea cealaltă.',
    'Vei primi o factură. O factură foarte lungă.',
    'Nu cedez nimic! ...Poate doar magazinul de suveniruri.',
    'Unul dintre avioanele tale e acum foc de artificii.',
    'Pilotul tău merge acasă pe jos. Încet.',
  ],
  da: [
    'Et par mursten. Min mormor mister flere i en storm.',
    'Du har lavet en skramme. Tillykke. Vi har lim.',
    'Er det hele den amerikanske hær? Jeg havde ventet mere larm.',
    'Bliv ved med at skyde. Souvenirbutikken sælger stumperne.',
    'Halvdelen er stadig mere, end du nogensinde bygger.',
    'Du har fået mine arkitekter til at græde. Nu er jeg vred.',
    'Et halvt monument er stadig et monument, cowboy.',
    'Mit forsikringsselskab holder meget nøje øje med dig.',
    'Kig op, amerikaner. Mine faldskærmstropper kommer.',
    'Jeg har ringet til mine fætre. Mine fætre har fly.',
    'Alle mine mænd er i luften. Duk dig.',
    'Springzonen er dit hoved. Velbekomme.',
    'Hver mand, hver morter, hvert missil. Nu kæmper vi.',
    'Ville du have krig? Her er hele hæren.',
    'Min brigade lander overalt. Du har intet sted at gemme dig.',
    'Himlen er lukket igen, cowboy. Gå hjem til fods.',
    'Fint. FINT! Den var alligevel grim.',
    'Ét skud mere, og jeg skifter side.',
    'Du får en regning. En meget lang regning.',
    'Jeg overgiver intet! ...Undtagen måske souvenirbutikken.',
    'Et af dine fly er nu et fyrværkeri.',
    'Din pilot går hjem til fods. Langsomt.',
  ],
  sv: [
    'Några tegelstenar. Min mormor tappar fler i en storm.',
    'Du har gjort en repa. Grattis. Vi har lim.',
    'Är det hela den amerikanska armén? Jag väntade mig mer oväsen.',
    'Fortsätt skjuta. Souvenirbutiken säljer bitarna.',
    'Hälften är fortfarande mer än du någonsin kommer att bygga.',
    'Du har fått mina arkitekter att gråta. Nu är jag arg.',
    'Ett halvt monument är fortfarande ett monument, cowboy.',
    'Mitt försäkringsbolag håller mycket noga ögonen på dig.',
    'Titta upp, amerikan. Mina fallskärmsjägare kommer.',
    'Jag har ringt mina kusiner. Mina kusiner har flygplan.',
    'Alla mina män är i luften. Ducka.',
    'Hoppzonen är ditt huvud. Smaklig måltid.',
    'Varje man, varje granatkastare, varje robot. Nu strider vi.',
    'Ville du ha krig? Här är hela armén.',
    'Min brigad landar överallt. Du har ingenstans att gömma dig.',
    'Himlen är stängd igen, cowboy. Gå hem till fots.',
    'Okej. OKEJ! Det var fult ändå.',
    'Ett skott till så byter jag sida.',
    'Du får en faktura. En mycket lång faktura.',
    'Jag ger upp ingenting! ...Utom kanske souvenirbutiken.',
    'Ett av dina plan är nu ett fyrverkeri.',
    'Din pilot går hem till fots. Långsamt.',
  ],
  no: [
    'Noen murstein. Bestemoren min mister flere i en storm.',
    'Du har laget en skramme. Gratulerer. Vi har lim.',
    'Er det hele den amerikanske hæren? Jeg ventet mer bråk.',
    'Bare fortsett å skyte. Suvenirbutikken selger bitene.',
    'Halvparten er fortsatt mer enn du noen gang kommer til å bygge.',
    'Du har fått arkitektene mine til å gråte. Nå er jeg sint.',
    'Et halvt monument er fortsatt et monument, cowboy.',
    'Forsikringsselskapet mitt følger deg veldig nøye.',
    'Se opp, amerikaner. Fallskjermjegerne mine kommer.',
    'Jeg har ringt fetterne mine. Fetterne mine har fly.',
    'Alle mennene mine er i lufta. Dukk.',
    'Hoppsonen er hodet ditt. Velbekomme.',
    'Hver mann, hver bombekaster, hvert missil. Nå kjemper vi.',
    'Ville du ha krig? Her er hele hæren.',
    'Brigaden min lander overalt. Du har ingen steder å gjemme deg.',
    'Himmelen er stengt igjen, cowboy. Gå hjem til fots.',
    'Greit. GREIT! Den var stygg uansett.',
    'Ett skudd til, så bytter jeg side.',
    'Du får en regning. En veldig lang regning.',
    'Jeg gir ikke fra meg noe! ...Unntatt kanskje suvenirbutikken.',
    'Et av flyene dine er nå et fyrverkeri.',
    'Piloten din går hjem til fots. Sakte.',
  ],
  is: [
    'Nokkrir múrsteinar. Amma mín tapar fleiri í stormi.',
    'Þú rispaðir hann. Til hamingju. Við eigum lím.',
    'Er þetta allur bandaríski herinn? Ég bjóst við meiri hávaða.',
    'Haltu áfram að skjóta. Minjagripabúðin selur brotin.',
    'Helmingurinn er samt meira en þú munt nokkurn tíma byggja.',
    'Þú lést arkitektana mína gráta. Nú er ég reiður.',
    'Hálfur minnisvarði er samt minnisvarði, kúreki.',
    'Tryggingafélagið mitt fylgist mjög vel með þér.',
    'Líttu upp, Kani. Fallhlífarhermennirnir mínir eru að koma.',
    'Ég hringdi í frændur mína. Frændur mínir eiga flugvélar.',
    'Allir mínir menn eru í loftinu. Beygðu þig.',
    'Lendingarsvæðið er hausinn á þér. Verði þér að góðu.',
    'Hver maður, hver sprengjuvarpa, hver flaug. Nú berjumst við.',
    'Vildirðu stríð? Hér er allur herinn.',
    'Herdeildin mín lendir alls staðar. Þú hefur hvergi að fela þig.',
    'Himinninn er lokaður aftur, kúreki. Gakktu heim.',
    'Allt í lagi. ALLT Í LAGI! Hann var hvort sem er ljótur.',
    'Eitt skot í viðbót og ég skipti um lið.',
    'Þú færð reikning. Mjög langan reikning.',
    'Ég gef ekkert eftir! ...Nema kannski minjagripabúðina.',
    'Ein af flugvélunum þínum er núna flugeldur.',
    'Flugmaðurinn þinn gengur heim. Hægt.',
  ],
  lt: [
    'Kelios plytos. Mano močiutė per audrą praranda daugiau.',
    'Tu jį įskėlei. Sveikinu. Turime klijų.',
    'Ar tai visa Amerikos kariuomenė? Tikėjausi daugiau triukšmo.',
    'Šaudyk toliau. Suvenyrų parduotuvė parduoda nuolaužas.',
    'Pusė vis tiek daugiau, nei tu kada nors pastatysi.',
    'Pravirkdei mano architektus. Dabar aš piktas.',
    'Pusė paminklo vis tiek paminklas, kaubojau.',
    'Mano draudimo bendrovė labai atidžiai tave stebi.',
    'Pažiūrėk aukštyn, amerikieti. Atskrenda mano desantininkai.',
    'Paskambinau pusbroliams. Mano pusbroliai turi lėktuvų.',
    'Visi mano vyrai danguje. Nusilenk.',
    'Nusileidimo zona yra tavo galva. Skanaus.',
    'Kiekvienas vyras, kiekvienas minosvaidis, kiekviena raketa. Dabar kovojame.',
    'Norėjai karo? Štai visa kariuomenė.',
    'Mano brigada leidžiasi visur. Neturi kur pasislėpti.',
    'Dangus vėl uždarytas, kaubojau. Eik namo pėsčias.',
    'Gerai. GERAI! Vis tiek buvo negražus.',
    'Dar vienas šūvis ir pereinu į kitą pusę.',
    'Gausi sąskaitą. Labai ilgą sąskaitą.',
    'Nieko neatiduosiu! ...Nebent suvenyrų parduotuvę.',
    'Vienas tavo lėktuvų dabar fejerverkas.',
    'Tavo pilotas eina namo pėsčias. Lėtai.',
  ],
  fi: [
    'Muutama tiili. Mummoni menettää myrskyssä enemmän.',
    'Naarmutit sitä. Onneksi olkoon. Meillä on liimaa.',
    'Onko tuo koko Yhdysvaltain armeija? Odotin enemmän meteliä.',
    'Ammu vain. Matkamuistomyymälä myy palasia.',
    'Puolikaskin on enemmän kuin sinä ikinä rakennat.',
    'Sait arkkitehtini itkemään. Nyt olen vihainen.',
    'Puolikas muistomerkki on yhä muistomerkki, cowboy.',
    'Vakuutusyhtiöni seuraa sinua hyvin tarkasti.',
    'Katso ylös, amerikkalainen. Laskuvarjojääkärini tulevat.',
    'Soitin serkuilleni. Serkuillani on lentokoneita.',
    'Kaikki mieheni ovat ilmassa. Kumarru.',
    'Pudotusalue on sinun pääsi. Hyvää ruokahalua.',
    'Jokainen mies, jokainen kranaatinheitin, jokainen ohjus. Nyt taistellaan.',
    'Halusitko sotaa? Tässä on koko armeija.',
    'Prikaatini laskeutuu kaikkialle. Sinulla ei ole paikkaa piiloutua.',
    'Taivas on taas kiinni, cowboy. Kävele kotiin.',
    'Hyvä on. HYVÄ ON! Se oli muutenkin ruma.',
    'Vielä yksi laukaus, niin vaihdan puolta.',
    'Saat laskun. Hyvin pitkän laskun.',
    'En luovuta mitään! ...Paitsi ehkä matkamuistomyymälän.',
    'Yksi koneistasi on nyt ilotulite.',
    'Lentäjäsi kävelee kotiin. Hitaasti.',
  ],
  sr: [
    'Par cigli. Moja baka izgubi više u oluji.',
    'Okrnjio si ga. Čestitam. Imamo lepak.',
    'To je cela američka vojska? Očekivao sam više buke.',
    'Samo pucaj. Suvenirnica prodaje komadiće.',
    'I pola je više nego što ćeš ti ikada sagraditi.',
    'Rasplakao si moje arhitekte. Sada sam ljut.',
    'Pola spomenika je i dalje spomenik, kauboju.',
    'Moja osiguravajuća kuća te veoma pažljivo prati.',
    'Pogledaj gore, Amerikanče. Dolaze moji padobranci.',
    'Pozvao sam rođake. Moji rođaci imaju avione.',
    'Svi moji ljudi su u vazduhu. Sagni se.',
    'Zona iskakanja je tvoja glava. Prijatno.',
    'Svaki čovek, svaki minobacač, svaka raketa. Sada se borimo.',
    'Hteo si rat? Evo ti cela vojska.',
    'Moja brigada sleće svuda. Nemaš gde da se sakriješ.',
    'Nebo je opet zatvoreno, kauboju. Idi kući peške.',
    'Dobro. DOBRO! Ionako je bio ružan.',
    'Još jedan hitac i prelazim na drugu stranu.',
    'Dobićeš račun. Veoma dugačak račun.',
    'Ništa ne predajem! ...Osim možda suvenirnice.',
    'Jedan tvoj avion je sada vatromet.',
    'Tvoj pilot ide kući peške. Polako.',
  ],
  vi: [
    'Vài viên gạch thôi. Bà tôi mất nhiều hơn thế trong một cơn bão.',
    'Anh làm nó sứt một chút. Chúc mừng. Chúng tôi có keo.',
    'Đó là cả quân đội Mỹ sao? Tôi tưởng sẽ ồn ào hơn.',
    'Cứ bắn tiếp đi. Cửa hàng lưu niệm đang bán các mảnh vỡ.',
    'Một nửa vẫn còn nhiều hơn những gì anh xây cả đời.',
    'Anh làm các kiến trúc sư của tôi khóc. Giờ tôi giận rồi.',
    'Nửa tượng đài vẫn là tượng đài, cao bồi.',
    'Công ty bảo hiểm của tôi đang theo dõi anh rất sát.',
    'Nhìn lên đi, người Mỹ. Lính dù của tôi đang tới.',
    'Tôi đã gọi anh em họ. Họ có máy bay.',
    'Mọi người lính còn lại của tôi đều ở trên trời. Cúi xuống.',
    'Bãi đáp là cái đầu của anh. Chúc ngon miệng.',
    'Mọi người lính, mọi khẩu súng cối, mọi tên lửa. Giờ mới đánh thật.',
    'Anh muốn chiến tranh à? Đây là cả quân đội.',
    'Lữ đoàn của tôi đổ bộ khắp nơi. Anh không có chỗ trốn.',
    'Bầu trời lại đóng rồi, cao bồi. Đi bộ về nhà đi.',
    'Được. ĐƯỢC! Đằng nào nó cũng xấu.',
    'Thêm một phát nữa là tôi đổi phe.',
    'Anh sẽ nhận được hóa đơn. Một hóa đơn rất dài.',
    'Tôi không giao nộp gì cả! ...Trừ có lẽ cửa hàng lưu niệm.',
    'Một chiếc máy bay của anh giờ thành pháo hoa rồi.',
    'Phi công của anh đang đi bộ về nhà. Chầm chậm.',
  ],
  ne: [
    'केही इँटा मात्र। मेरी हजुरआमाले आँधीमा योभन्दा धेरै गुमाउनुहुन्छ।',
    'तिमीले अलिकति चोइट्यायौ। बधाई छ। हामीसँग गम छ।',
    'के यही हो पूरै अमेरिकी सेना? मैले अझ धेरै होहल्ला सोचेको थिएँ।',
    'हान्दै जाऊ। उपहार पसलले टुक्राहरू बेचिरहेको छ।',
    'आधा पनि तिमीले जीवनभर बनाउने भन्दा धेरै हो।',
    'तिमीले मेरा वास्तुकारहरूलाई रुवायौ। अब म रिसाएँ।',
    'आधा स्मारक पनि स्मारक नै हो, काउब्वाय।',
    'मेरो बीमा कम्पनीले तिमीलाई नजिकबाट हेरिरहेको छ।',
    'माथि हेर, अमेरिकी। मेरा प्याराट्रुपरहरू आउँदैछन्।',
    'मैले मेरा भाइहरूलाई बोलाएँ। उनीहरूसँग हवाइजहाज छ।',
    'मेरा बाँकी सबै मान्छे आकाशमा छन्। टाउको निहुराऊ।',
    'झर्ने ठाउँ तिम्रो टाउको हो। मज्जाले खाऊ।',
    'हरेक सिपाही, हरेक मोर्टार, हरेक मिसाइल। अब साँच्चै लडौँ।',
    'युद्ध चाहिएको थियो? यो रह्यो पूरै सेना।',
    'मेरो ब्रिगेड जताततै झर्दैछ। तिमीसँग लुक्ने ठाउँ छैन।',
    'आकाश फेरि बन्द भयो, काउब्वाय। हिँडेर घर जाऊ।',
    'ठिकै छ। ठिकै छ! जे भए पनि यो कुरूप थियो।',
    'अर्को एक गोली, अनि म पक्ष बदल्छु।',
    'तिमीलाई बिल आउनेछ। धेरै लामो बिल।',
    'म केही पनि दिन्नँ! ...उपहार पसलबाहेक।',
    'तिम्रो एउटा हवाइजहाज अब आतिशबाजी भयो।',
    'तिम्रो पाइलट हिँडेर घर जाँदैछ। बिस्तारै।',
  ],
  hi: [
    'कुछ ईंटें बस। मेरी दादी आँधी में इससे ज़्यादा खो देती हैं।',
    'थोड़ा सा टूटा है। बधाई हो। हमारे पास गोंद है।',
    'क्या यही पूरी अमेरिकी सेना है? मुझे ज़्यादा शोर की उम्मीद थी।',
    'चलाते रहो। स्मृति-चिह्न की दुकान टुकड़े बेच रही है।',
    'आधा भी उससे ज़्यादा है जितना तुम ज़िंदगी भर बनाओगे।',
    'तुमने मेरे वास्तुकारों को रुला दिया। अब मुझे गुस्सा आ गया है।',
    'आधा स्मारक भी स्मारक ही है, काउबॉय।',
    'मेरी बीमा कंपनी तुम पर बहुत क़रीब से नज़र रख रही है।',
    'ऊपर देखो, अमेरिकी। मेरे पैराट्रूपर आ रहे हैं।',
    'मैंने अपने चचेरे भाइयों को बुलाया है। उनके पास हवाई जहाज़ हैं।',
    'मेरे बाक़ी सारे आदमी आसमान में हैं। सिर झुकाओ।',
    'उतरने की जगह तुम्हारा सिर है। मज़े करो।',
    'हर सिपाही, हर मोर्टार, हर मिसाइल। अब असली लड़ाई होगी।',
    'युद्ध चाहिए था? यह रही पूरी सेना।',
    'मेरी ब्रिगेड हर जगह उतर रही है। तुम्हारे छिपने की कोई जगह नहीं।',
    'आसमान फिर बंद हो गया, काउबॉय। पैदल घर जाओ।',
    'ठीक है। ठीक है! वैसे भी बदसूरत था।',
    'एक और गोला, और मैं पाला बदल लूँगा।',
    'तुम्हें एक बिल मिलेगा। बहुत लंबा बिल।',
    'मैं कुछ नहीं दूँगा! ...शायद स्मृति-चिह्न की दुकान को छोड़कर।',
    'तुम्हारा एक हवाई जहाज़ अब आतिशबाज़ी बन गया है।',
    'तुम्हारा पायलट पैदल घर जा रहा है। धीरे-धीरे।',
  ],
  ur: [
    'بس چند اینٹیں۔ میری دادی آندھی میں اس سے زیادہ کھو دیتی ہیں۔',
    'تم نے تھوڑا سا توڑ دیا۔ مبارک ہو۔ ہمارے پاس گوند ہے۔',
    'کیا یہی پوری امریکی فوج ہے؟ مجھے زیادہ شور کی توقع تھی۔',
    'چلاتے رہو۔ تحفوں کی دکان ٹکڑے بیچ رہی ہے۔',
    'آدھا بھی اس سے زیادہ ہے جتنا تم ساری زندگی میں بناؤ گے۔',
    'تم نے میرے معماروں کو رُلا دیا۔ اب مجھے غصہ آ گیا ہے۔',
    'آدھی یادگار بھی یادگار ہی ہے، کاؤبوائے۔',
    'میری انشورنس کمپنی تم پر بہت قریب سے نظر رکھ رہی ہے۔',
    'اوپر دیکھو، امریکی۔ میرے چھاتہ بردار آ رہے ہیں۔',
    'میں نے اپنے کزنز کو بلایا ہے۔ ان کے پاس ہوائی جہاز ہیں۔',
    'میرے باقی سارے آدمی آسمان میں ہیں۔ سر جھکاؤ۔',
    'اترنے کی جگہ تمہارا سر ہے۔ نوشِ جان۔',
    'ہر سپاہی، ہر مارٹر، ہر میزائل۔ اب اصل لڑائی ہوگی۔',
    'جنگ چاہیے تھی؟ یہ رہی پوری فوج۔',
    'میری بریگیڈ ہر جگہ اتر رہی ہے۔ تمہارے چھپنے کی کوئی جگہ نہیں۔',
    'آسمان پھر بند ہو گیا، کاؤبوائے۔ پیدل گھر جاؤ۔',
    'ٹھیک ہے۔ ٹھیک ہے! ویسے بھی بدصورت تھا۔',
    'ایک اور گولہ، اور میں طرف بدل لوں گا۔',
    'تمہیں ایک بل ملے گا۔ بہت لمبا بل۔',
    'میں کچھ نہیں دوں گا! ...شاید تحفوں کی دکان کے سوا۔',
    'تمہارا ایک ہوائی جہاز اب آتش بازی بن گیا ہے۔',
    'تمہارا پائلٹ پیدل گھر جا رہا ہے۔ آہستہ آہستہ۔',
  ],
  fa: [
    'فقط چند آجر. مادربزرگم توی طوفان بیشتر از این از دست می‌دهد.',
    'یک کم خراشش دادی. تبریک. ما چسب داریم.',
    'این کل ارتش آمریکاست؟ انتظار سروصدای بیشتری داشتم.',
    'به شلیک ادامه بده. مغازهٔ سوغاتی تکه‌هایش را می‌فروشد.',
    'نصفش هم از هر چیزی که تو در عمرت بسازی بیشتر است.',
    'معمارهایم را به گریه انداختی. حالا عصبانی شدم.',
    'نصف یک بنای یادبود هم بنای یادبود است، کابوی.',
    'شرکت بیمه‌ام تو را از نزدیک زیر نظر دارد.',
    'بالا را نگاه کن، آمریکایی. چتربازهایم دارند می‌آیند.',
    'پسرعموهایم را خبر کردم. پسرعموهایم هواپیما دارند.',
    'همهٔ افراد باقی‌مانده‌ام در آسمان‌اند. سرت را بدزد.',
    'منطقهٔ فرود سر توست. نوش جان.',
    'هر سرباز، هر خمپاره، هر موشک. حالا جنگ واقعی است.',
    'جنگ می‌خواستی؟ این هم کل ارتش.',
    'تیپ من همه‌جا فرود می‌آید. جایی برای پنهان شدن نداری.',
    'آسمان دوباره بسته شد، کابوی. پیاده برگرد خانه.',
    'باشه. باشه! به هر حال زشت بود.',
    'یک گلولهٔ دیگر، و طرفم را عوض می‌کنم.',
    'یک صورت‌حساب برایت می‌آید. یک صورت‌حساب خیلی بلند.',
    'هیچ چیز تحویل نمی‌دهم! ...شاید جز مغازهٔ سوغاتی.',
    'یکی از هواپیماهایت حالا آتش‌بازی شده.',
    'خلبانت پیاده دارد به خانه می‌رود. آهسته.',
  ],
  uz: [
    "Bir nechta g'isht, xolos. Buvim bo'ronda bundan ko'pini yo'qotadi.",
    "Sen uni sal o'yib qo'yding. Tabriklayman. Bizda yelim bor.",
    "Bu butun Amerika armiyasimi? Men ko'proq shovqin kutgandim.",
    "Otishda davom et. Sovg'alar do'koni parchalarini sotyapti.",
    "Yarmi ham sen umr bo'yi quradiganingdan ko'p.",
    "Me'morlarimni yig'latding. Endi men jahldorman.",
    'Yarim yodgorlik ham yodgorlik, kovboy.',
    "Sug'urta kompaniyam seni juda yaqindan kuzatyapti.",
    'Tepaga qara, amerikalik. Desantchilarim kelyapti.',
    'Amakivachchalarimni chaqirdim. Ularning samolyotlari bor.',
    'Qolgan barcha odamlarim osmonda. Bosh egib tur.',
    'Tushish joyi — sening boshing. Yoqimli ishtaha.',
    'Har bir askar, har bir minomyot, har bir raketa. Endi chinakam jang.',
    'Urush xohlaganmiding? Mana butun armiya.',
    "Brigadam hamma joyga tushyapti. Yashirinadigan joying yo'q.",
    'Osmon yana yopildi, kovboy. Uyingga piyoda qayt.',
    'Mayli. MAYLI! Baribir xunuk edi.',
    "Yana bitta o'q, va men tomonimni o'zgartiraman.",
    'Senga hisob keladi. Juda uzun hisob.',
    "Hech narsani bermayman! ...Sovg'alar do'konidan tashqari.",
    'Samolyotlaringdan biri endi otashbazi.',
    'Uchuvching uyiga piyoda ketyapti. Sekin-sekin.',
  ],
  az: [
    'Bir neçə kərpic, vəssalam. Nənəm fırtınada bundan çoxunu itirir.',
    'Onu bir az qırdın. Təbrik edirəm. Bizdə yapışqan var.',
    'Bu bütün Amerika ordusudur? Daha çox səs-küy gözləyirdim.',
    'Atmağa davam et. Suvenir mağazası qırıntıları satır.',
    'Yarısı da sənin ömrün boyu tikəcəyindən çoxdur.',
    'Memarlarımı ağlatdın. İndi mən hirsliyəm.',
    'Yarım abidə də abidədir, kovboy.',
    'Sığorta şirkətim səni çox yaxından izləyir.',
    'Yuxarı bax, amerikalı. Desantçılarım gəlir.',
    'Əmioğlularımı çağırdım. Onların təyyarələri var.',
    'Qalan bütün adamlarım göydədir. Başını aşağı sal.',
    'Enmə zonası sənin başındır. Nuş olsun.',
    'Hər əsgər, hər minaatan, hər raket. İndi əsl döyüşdür.',
    'Müharibə istəyirdin? Budur bütün ordu.',
    'Briqadam hər yerə enir. Gizlənməyə yerin yoxdur.',
    'Səma yenə bağlandı, kovboy. Evə piyada qayıt.',
    'Yaxşı. YAXŞI! Onsuz da çirkin idi.',
    'Bir atəş də, və mən tərəf dəyişirəm.',
    'Sənə hesab gələcək. Çox uzun bir hesab.',
    'Heç nə vermirəm! ...Bəlkə suvenir mağazasından başqa.',
    'Təyyarələrindən biri indi fişəngdir.',
    'Pilotun evə piyada gedir. Yavaş-yavaş.',
  ],
};

/** Who speaks what, by the defender's nation. */
const LANG = {
  fr: 'fr', be: 'fr', ci: 'fr', ch: 'fr', ca: 'fr',
  es: 'es', mx: 'es', gt: 'es', pe: 'es', cu: 'es', ar: 'es', co: 'es',
  pt: 'pt', br: 'pt', it: 'it', de: 'de', at: 'de', ru: 'ru', kz: 'kk',
  eg: 'ar', ae: 'ar', ma: 'ar', kw: 'ar', sa: 'ar', lb: 'ar', iq: 'ar',
  gr: 'el', tr: 'tr', jp: 'ja', cn: 'zh', tw: 'zh-tw', kr: 'ko', kp: 'ko',
  th: 'th', mm: 'my', kh: 'km', id: 'id', my: 'ms', hu: 'hu', cz: 'cs',
  pl: 'pl', ro: 'ro', dk: 'da', se: 'sv', no: 'no', is: 'is', lt: 'lt',
  fi: 'fi', rs: 'sr', vn: 'vi', np: 'ne', in: 'hi', pk: 'ur', ir: 'fa',
  uz: 'uz', az: 'az',
};

/** For the harness: every language has a line for every meaning. */
export const CHATTER_CHECK = () => {
  const n = ORDER.reduce((a, k) => a + MEAN[k].length, 0);
  return Object.entries(T).filter(([, v]) => v.length !== n).map(([k, v]) => `${k}: ${v.length} of ${n}`);
};

/**
 * The defender's voice for a level: `say(moment)` returns `{ line, sub }`,
 * `sub` the English when he is not speaking it, drawing without repeats
 * until a moment's list runs dry.
 */
export function voiceFor(levelId) {
  const native = !!STANDOFF_SUB[levelId];
  const code = DEFENDER_OF[levelId];
  const lang = native ? LANG[code] : null;
  const table = lang && T[lang];
  const used = new Map();
  const draw = (k, n) => {
    const left = [];
    const u = used.get(k) || new Set();
    for (let i = 0; i < n; i++) if (!u.has(i)) left.push(i);
    const pool = left.length ? left : [...Array(n).keys()];
    if (!left.length) u.clear();
    const i = pool[Math.floor(Math.random() * pool.length)];
    u.add(i);
    used.set(k, u);
    return i;
  };
  return {
    native: !!table,
    lang,
    say(moment) {
      const mean = MEAN[moment];
      if (!mean) return null;
      if (table) {
        const at = ORDER.slice(0, ORDER.indexOf(moment)).reduce((a, k) => a + MEAN[k].length, 0);
        const i = draw(moment, mean.length);
        return { line: table[at + i], sub: mean[i] };
      }
      const all = [...mean, ...(EN_EXTRA[moment] || [])];
      return { line: all[draw(moment, all.length)], sub: null };
    },
  };
}
