/**
 * What the defender actually said.
 *
 * In the stand-off he speaks his own language and the General never
 * understands a word of it, which is the joke; the player is let in on it
 * here, in a line of English under his own. A level listed here is one whose
 * defender speaks his own language, and he goes on speaking it in the fight
 * (see `chatter.js`): he does not drop into English at the first shell. A
 * level not listed is one where he speaks English from the start.
 */
export const STANDOFF_SUB = {
  paris: 'Go choke on a baguette.',
  giza: 'Climb up this pyramid then, you fat kid. Come and get it.',
  chichen: "You're a thousand years late. We buried this once already and built on top of it again.",
  pisa: "It has leaned for eight hundred years, American. You won't last eight minutes in this sun.",
  moscow: "Ivan blinded the architect so he could never build another. We'll leave you your eyes. Watch.",
  rio: "He has held his arms open for a century. He won't lower them, not even for you.",
  athens: 'Persians, Romans, Turks, the English. All came for the marbles. None left with what they came for.',
  istanbul: "It has stood fifteen hundred years of earthquakes, American. You won't last a weekend.",
  cologne: "The bombers couldn't do it in 1945, American. You with your four guns certainly won't.",
  himeji: "For four hundred years nobody took this castle. You haven't even taken your shoes off.",
  dubai: "Eight hundred metres, American. Your guns won't reach halfway.",
  petronas: 'Two towers, one bridge. Shoot that bridge: it holds nothing up.',
  potala: 'This wall is thicker than your gun barrels. You are shooting a mountain, not a house.',
  florence: "Brunelleschi built that dome without scaffolding. You don't even know what that is.",
  segovia: "The Romans raised it without cement, gringo. You can't even make a tortilla.",
  tokyotower: "This tower was made by melting down your country's old tanks. Want them back?",
  budapest: 'Here even the paprika is hotter than your artillery, American.',
  sagrada: 'Gaudí said his client was in no hurry. God is in no hurry with you either, American.',
  neuschwanstein: "That's the castle from your Disney film, American. You didn't even invent that yourselves.",
  montstmichel: 'Here the tide comes in as fast as a galloping horse. And you, fatso, can you run fast?',
  pena: "You look like someone who's never eaten a custard tart in his life, American.",
  hassan: 'The minaret stands on the sea, American, and the sea kneels to no one.',
  kuwait: "These towers didn't fall in '90, American, and they won't fall today.",
  karnak: "Son, this is a temple, not a McDonald's. Take off the sunglasses and look properly.",
  forbidden: "You can't even use chopsticks, and you want to take the Forbidden City?",
  gyeongbok: 'This palace burned twice and was rebuilt twice. You will only be the third time.',
  watarun: 'This prang has stood by the river for two hundred years. Your guns are just noise in the rain.',
  shwedagon: 'Shwedagon has outlasted earthquakes and emperors. You are nothing.',
  angkor: 'Angkor Wat has stood for more than eight hundred years. You cannot bring it down.',
  borobudur: 'Borobudur slept under the ash for a thousand years and woke again. You are just more dust.',
  tikal: "The Maya raised this without wheels or metal, American. You're just another storm.",
  teotihuacan: "The Aztecs found this city already abandoned and didn't dare touch it. Neither should you.",
  machupicchu: "The Incas cut these stones so not even a knife gets in. Your shells won't either.",
  greatwall: "Where you're standing, Meng Jiangnü wept a stretch of the Wall down. Your crying won't help.",
  milan: "The Duomo was never finished. And you won't finish it.",
  stvitus: "Here we throw people out of windows, American. It's in our blood.",
  ulm: 'Einstein was born here. Not even he could save your sums.',
  brandenburg: "Your president said it here: tear down this wall. He didn't mean the gate.",
  stephansdom: 'We are Austrians, not Germans. Remember that before you die.',
  hohensalzburg: "The funicular costs sixteen euros, American. For you it's closed today.",
  versailles: 'Even Marie Antoinette had more brains than you. And she lost her head.',
  chambord: 'Two staircases that never meet. Like you and victory.',
  seville: 'Columbus is buried here. Not even dead has he surrendered.',
  alhambra: 'The Alhambra is poetry in stone. All you can read is a firing table.',
  malbork: "The Teutonic Knights built it, we rebuilt it. We'll rebuild it after you too.",
  warsaw: "They say the best view is from the top, because from there you can't see it.",
  bran: 'Vlad never lived here. But we will bury you here.',
  bucharest: 'It has more rooms than you have shells.',
  kronborg: 'Holger the Dane sleeps in the cellar. He wakes when Denmark is in danger.',
  stockholm: "You won't find assembly instructions for taking this apart.",
  hallgrimskirkja: 'We have no army. We have a church and a great deal of wind.',
  trakai: "Vytautas the Great lived here. He didn't like guests.",
  winterpalace: "Your tourists pay twenty dollars to get in here. You'll pay more.",
  belem: "From here we set out to discover the world. You've only discovered the wrong way.",
  nidaros: 'Saint Olav lies here. He was a Viking king before he was a saint.',
  helsinki: "We didn't give in during the Winter War. We won't now.",
  chillon: 'Switzerland is neutral, General. Not that neutral.',
  saintsava: "We spent a hundred years building this church. You won't knock it down in a day.",
  taipei101: 'This building has taken typhoons and earthquakes. What are you?',
  shanghaitower: "The tower twists a hundred and twenty degrees against the typhoons. You can't twist it.",
  wildgoose: "Xuanzang walked seventeen years to fetch the scriptures. You won't last seventeen minutes.",
  landmark81: "This is the tallest building in Vietnam. You won't make it any shorter.",
  boudhanath: 'This stupa has survived many earthquakes. You are just one more.',
  victoriamemorial: 'This marble came from the same quarry as the Taj Mahal. It will last as long.',
  hawamahal: 'The wind blows straight through the Palace of Winds. So will your shells.',
  redfort: 'These walls have seen the Mughals, the British and freedom. You are nothing.',
  gatewayindia: 'This gate is not for coming in. It is for leaving.',
  osaka: 'This castle has burned many times. Every time, we rebuilt it.',
  kinkakuji: 'The Golden Pavilion burned once. There will not be a second time.',
  juche: 'Our tower will stand forever.',
  monas: 'That gold belongs to the people of Indonesia.',
  prambanan: 'This temple has survived earthquakes and volcanoes.',
  minarpakistan: "This minaret is the symbol of the nation's resolve.",
  bayterek: "No one can take the Samruk's egg.",
  registan: 'Ulugh Beg taught the stars here.',
  flametowers: 'This is the land of fire. We are not afraid of fire.',
  azadi: "This tower is built of eight thousand stones. You can't move even one.",
  kingdomcentre: 'This tower carries a bridge in the sky.',
  baalbek: 'These stones are bigger than your tank.',
  ur: 'This is three thousand seven hundred years older than your country.',
  djoser: 'Imhotep built this before anyone knew how.',
  yamoussoukro: "This basilica is bigger than Saint Peter's in Rome.",
  frontenac: "Je me souviens. You, we'll forget.",
  capitolio: 'Our Capitol is taller than yours. And prettier.',
  bellasartes: 'The Palace has sunk four metres. It has never surrendered.',
  teatroamazonas: 'Even Caruso wanted to sing here.',
  obelisco: 'Hey, the Obelisk belongs to everyone in Buenos Aires.',
  cartagena: 'Blas de Lezo held this place with one leg, one arm and one eye.',
};
