// Generated by tools/edinburgh_plan.py from the survey and the terrain bake.
// Do not edit: change the wings in the tool and run it again.
export const PLAN = {
 "wings": [
  {
   "name": "Royal Palace",
   "tag": "palace",
   "kind": "hall",
   "cx": 30.6,
   "cz": 56.85,
   "len": 38.5,
   "wid": 19.5,
   "ry": -0.0156,
   "h": 15.3,
   "found": -32,
   "grade": 0.0
  },
  {
   "name": "Great Hall",
   "tag": "greathall",
   "kind": "hall",
   "cx": 6.9,
   "cz": 69.9,
   "len": 26.04,
   "wid": 12.6,
   "ry": 1.6246,
   "h": 13.0,
   "found": -26,
   "grade": 0.0
  },
  {
   "name": "Queen Anne Building",
   "tag": "greathall",
   "kind": "hall",
   "cx": -16.35,
   "cz": 58.6,
   "len": 37.72,
   "wid": 16.3,
   "ry": 0.1303,
   "h": 15.0,
   "found": -49,
   "grade": 0.0
  },
  {
   "name": "War Memorial",
   "tag": "memorial",
   "kind": "hall",
   "cx": 5.1,
   "cz": 28.9,
   "len": 36.57,
   "wid": 13.0,
   "ry": 1.7135,
   "h": 14.5,
   "found": -3,
   "grade": 0.0
  },
  {
   "name": "War Memorial apse",
   "tag": "memorial",
   "kind": "hall",
   "cx": 3.0,
   "cz": 17.5,
   "len": 9.02,
   "wid": 8.0,
   "ry": -3.075,
   "h": 11.0,
   "found": -3,
   "grade": 0.0
  },
  {
   "name": "New Barracks",
   "tag": "barracks",
   "kind": "hall",
   "cx": -84.9,
   "cz": 38.25,
   "len": 64.6,
   "wid": 17.0,
   "ry": 0.6327,
   "h": 13.0,
   "found": -52,
   "grade": 0.0
  },
  {
   "name": "Military Prison",
   "tag": "barracks",
   "kind": "hall",
   "cx": -45.55,
   "cz": 56.35,
   "len": 13.7,
   "wid": 14.0,
   "ry": 0.0073,
   "h": 14.4,
   "found": -33,
   "grade": 0.0
  },
  {
   "name": "Royal Scots, west",
   "tag": "barracks",
   "kind": "hall",
   "cx": -37.0,
   "cz": 36.5,
   "len": 18.93,
   "wid": 9.5,
   "ry": 1.6873,
   "h": 12.4,
   "found": -3,
   "grade": 0.0
  },
  {
   "name": "Royal Scots, north",
   "tag": "barracks",
   "kind": "hall",
   "cx": -30.3,
   "cz": 47.5,
   "len": 11.02,
   "wid": 8.6,
   "ry": 0.0545,
   "h": 12.4,
   "found": -6,
   "grade": 0.0
  },
  {
   "name": "Hospital, north",
   "tag": "hospital",
   "kind": "hall",
   "cx": -119.5,
   "cz": -49.8,
   "len": 35.13,
   "wid": 12.0,
   "ry": 1.6563,
   "h": 14.7,
   "found": -41,
   "grade": 0.0
  },
  {
   "name": "Hospital, east",
   "tag": "hospital",
   "kind": "hall",
   "cx": -104.7,
   "cz": -35.0,
   "len": 18.01,
   "wid": 9.0,
   "ry": 0.0333,
   "h": 14.7,
   "found": -13,
   "grade": 0.0
  },
  {
   "name": "Hospital, west",
   "tag": "hospital",
   "kind": "hall",
   "cx": -131.4,
   "cz": -24.5,
   "len": 31.06,
   "wid": 7.0,
   "ry": 0.0644,
   "h": 14.1,
   "found": -27,
   "grade": 0.0
  },
  {
   "name": "War Museum",
   "tag": "hospital",
   "kind": "hall",
   "cx": -113.9,
   "cz": -10.35,
   "len": 32.49,
   "wid": 10.2,
   "ry": 1.7036,
   "h": 14.1,
   "found": -10,
   "grade": 0.0
  },
  {
   "name": "Governor's House",
   "tag": "governor",
   "kind": "hall",
   "cx": -80.55,
   "cz": -0.5,
   "len": 33.97,
   "wid": 11.0,
   "ry": 0.4215,
   "h": 10.1,
   "found": -3,
   "grade": 0.0
  },
  {
   "name": "Cartsheds",
   "tag": "governor",
   "kind": "hall",
   "cx": -80.55,
   "cz": -43.45,
   "len": 22.49,
   "wid": 14.4,
   "ry": 2.3813,
   "h": 13.1,
   "found": -29,
   "grade": 0.0
  },
  {
   "name": "Cartsheds, west",
   "tag": "governor",
   "kind": "hall",
   "cx": -86.75,
   "cz": -53.2,
   "len": 17.04,
   "wid": 8.0,
   "ry": 2.3686,
   "h": 12.0,
   "found": -42,
   "grade": 0.0
  },
  {
   "name": "Ordnance store",
   "tag": "governor",
   "kind": "hall",
   "cx": -38.5,
   "cz": -6.7,
   "len": 18.63,
   "wid": 9.0,
   "ry": -0.0537,
   "h": 11.1,
   "found": -3,
   "grade": 0.0
  },
  {
   "name": "Mills Mount range",
   "tag": "governor",
   "kind": "hall",
   "cx": -40.8,
   "cz": 11.1,
   "len": 10.63,
   "wid": 11.0,
   "ry": 1.3623,
   "h": 6.0,
   "found": -3,
   "grade": 0.0
  },
  {
   "name": "St Margaret's Chapel",
   "tag": "chapel",
   "kind": "chapel",
   "cx": -18.0,
   "cz": -8.2,
   "len": 9.21,
   "wid": 5.0,
   "ry": 1.6142,
   "h": 8.0,
   "found": -3,
   "grade": 0.0
  },
  {
   "name": "Argyle Tower",
   "tag": "argyle",
   "kind": "tower",
   "cx": 4.9,
   "cz": -26.15,
   "len": 14.38,
   "wid": 8.4,
   "ry": -0.7313,
   "h": 13.0,
   "found": -3,
   "grade": 0.0
  },
  {
   "name": "Argyle Battery",
   "tag": "argyle",
   "kind": "battery",
   "cx": 35.25,
   "cz": -19.2,
   "len": 38.95,
   "wid": 9.0,
   "ry": 1.2141,
   "h": 5.0,
   "found": -3,
   "grade": 0.0
  },
  {
   "name": "Gatehouse",
   "tag": "gatehouse",
   "kind": "gate",
   "cx": 70.95,
   "cz": 11.5,
   "len": 33.36,
   "wid": 9.4,
   "ry": 0.1474,
   "h": 12.7,
   "found": -5,
   "grade": 0.0
  }
 ],
 "curtain": [
  {
   "x": 78.35,
   "z": 31.65,
   "found": -14,
   "grade": 0.0
  },
  {
   "x": 76.85,
   "z": 37.48,
   "found": -16,
   "grade": 0.0
  },
  {
   "x": 74.91,
   "z": 43.25,
   "found": -14,
   "grade": -0.8
  },
  {
   "x": 75.03,
   "z": 50.61,
   "found": -16,
   "grade": -3.0
  },
  {
   "x": 70.13,
   "z": 54.79,
   "found": -13,
   "grade": 0.0
  },
  {
   "x": 64.28,
   "z": 57.88,
   "found": -15,
   "grade": -0.5
  },
  {
   "x": 55.92,
   "z": 57.91,
   "found": -15,
   "grade": 0.0
  },
  {
   "x": 48.53,
   "z": 57.84,
   "found": -15,
   "grade": 0.0
  },
  {
   "x": 42.03,
   "z": 57.84,
   "found": -14,
   "grade": 0.0
  },
  {
   "x": 38.15,
   "z": 61.06,
   "found": -17,
   "grade": 0.0
  },
  {
   "x": 34.04,
   "z": 64.01,
   "found": -16,
   "grade": -1.3
  },
  {
   "x": 28.67,
   "z": 64.4,
   "found": -13,
   "grade": 0.0
  },
  {
   "x": 24.63,
   "z": 67.66,
   "found": -16,
   "grade": -0.6
  },
  {
   "x": 19.43,
   "z": 67.77,
   "found": -14,
   "grade": -0.3
  },
  {
   "x": 14.45,
   "z": 67.98,
   "found": -14,
   "grade": -0.3
  },
  {
   "x": 9.53,
   "z": 67.83,
   "found": -14,
   "grade": 0.0
  },
  {
   "x": 4.74,
   "z": 67.83,
   "found": -12,
   "grade": 0.0
  },
  {
   "x": 0.0,
   "z": 71.0,
   "found": -16,
   "grade": -2.5
  },
  {
   "x": -4.74,
   "z": 67.83,
   "found": -12,
   "grade": 0.0
  },
  {
   "x": -9.53,
   "z": 67.83,
   "found": -19,
   "grade": -1.4
  },
  {
   "x": -13.51,
   "z": 63.58,
   "found": -19,
   "grade": -0.8
  },
  {
   "x": -16.81,
   "z": 58.64,
   "found": -13,
   "grade": 0.0
  },
  {
   "x": -20.86,
   "z": 57.32,
   "found": -18,
   "grade": 0.0
  },
  {
   "x": -25.62,
   "z": 57.55,
   "found": -19,
   "grade": -2.3
  },
  {
   "x": -30.52,
   "z": 57.39,
   "found": -18,
   "grade": -2.1
  },
  {
   "x": -36.03,
   "z": 57.67,
   "found": -18,
   "grade": -2.0
  },
  {
   "x": -40.56,
   "z": 55.82,
   "found": -14,
   "grade": 0.0
  },
  {
   "x": -45.64,
   "z": 54.39,
   "found": -16,
   "grade": 0.0
  },
  {
   "x": -48.97,
   "z": 50.71,
   "found": -13,
   "grade": 0.0
  },
  {
   "x": -56.48,
   "z": 50.85,
   "found": -17,
   "grade": -0.8
  },
  {
   "x": -61.07,
   "z": 47.71,
   "found": -12,
   "grade": 0.0
  },
  {
   "x": -70.88,
   "z": 47.81,
   "found": -16,
   "grade": -0.5
  },
  {
   "x": -77.08,
   "z": 44.5,
   "found": -15,
   "grade": 0.0
  },
  {
   "x": -82.24,
   "z": 40.11,
   "found": -15,
   "grade": -2.3
  },
  {
   "x": -84.84,
   "z": 34.28,
   "found": -15,
   "grade": -2.8
  },
  {
   "x": -85.6,
   "z": 27.81,
   "found": -13,
   "grade": 0.0
  },
  {
   "x": -92.66,
   "z": 23.1,
   "found": -14,
   "grade": -0.7
  },
  {
   "x": -99.47,
   "z": 17.54,
   "found": -10,
   "grade": 0.0
  },
  {
   "x": -113.38,
   "z": 11.92,
   "found": -15,
   "grade": -1.6
  },
  {
   "x": -123.92,
   "z": 4.33,
   "found": -10,
   "grade": -1.6
  },
  {
   "x": -130.92,
   "z": -4.57,
   "found": -12,
   "grade": -2.1
  },
  {
   "x": -131.28,
   "z": -13.8,
   "found": -12,
   "grade": -2.7
  },
  {
   "x": -124.09,
   "z": -21.88,
   "found": -11,
   "grade": -1.5
  },
  {
   "x": -120.8,
   "z": -30.12,
   "found": -12,
   "grade": -2.2
  },
  {
   "x": -113.65,
   "z": -36.93,
   "found": -10,
   "grade": -0.3
  },
  {
   "x": -106.63,
   "z": -43.08,
   "found": -12,
   "grade": -1.1
  },
  {
   "x": -98.42,
   "z": -48.0,
   "found": -18,
   "grade": -0.7
  },
  {
   "x": -83.14,
   "z": -48.0,
   "found": -15,
   "grade": 0.0
  },
  {
   "x": -70.88,
   "z": -47.81,
   "found": -14,
   "grade": 0.0
  },
  {
   "x": -65.4,
   "z": -51.1,
   "found": -19,
   "grade": -1.7
  },
  {
   "x": -57.97,
   "z": -52.19,
   "found": -15,
   "grade": 0.0
  },
  {
   "x": -52.45,
   "z": -54.31,
   "found": -14,
   "grade": 0.0
  },
  {
   "x": -48.53,
   "z": -57.84,
   "found": -15,
   "grade": 0.0
  },
  {
   "x": -44.08,
   "z": -60.68,
   "found": -17,
   "grade": -1.8
  },
  {
   "x": -38.15,
   "z": -61.06,
   "found": -18,
   "grade": -2.1
  },
  {
   "x": -30.52,
   "z": -57.39,
   "found": -13,
   "grade": 0.0
  },
  {
   "x": -25.62,
   "z": -57.55,
   "found": -16,
   "grade": 0.0
  },
  {
   "x": -20.86,
   "z": -57.32,
   "found": -16,
   "grade": 0.0
  },
  {
   "x": -16.4,
   "z": -57.2,
   "found": -16,
   "grade": 0.0
  },
  {
   "x": -12.16,
   "z": -57.22,
   "found": -15,
   "grade": 0.0
  },
  {
   "x": -8.0,
   "z": -56.94,
   "found": -15,
   "grade": 0.0
  },
  {
   "x": -4.01,
   "z": -57.36,
   "found": -17,
   "grade": 0.0
  },
  {
   "x": -0.0,
   "z": -57.0,
   "found": -17,
   "grade": -1.0
  },
  {
   "x": 4.01,
   "z": -57.36,
   "found": -17,
   "grade": 0.0
  },
  {
   "x": 8.0,
   "z": -56.94,
   "found": -13,
   "grade": 0.0
  },
  {
   "x": 12.89,
   "z": -60.65,
   "found": -16,
   "grade": 0.0
  },
  {
   "x": 18.47,
   "z": -64.4,
   "found": -14,
   "grade": 0.0
  },
  {
   "x": 24.63,
   "z": -67.66,
   "found": -15,
   "grade": -1.3
  },
  {
   "x": 30.3,
   "z": -68.06,
   "found": -14,
   "grade": -0.0
  },
  {
   "x": 34.27,
   "z": -64.46,
   "found": -12,
   "grade": 0.0
  },
  {
   "x": 40.27,
   "z": -64.45,
   "found": -14,
   "grade": 0.0
  },
  {
   "x": 47.02,
   "z": -64.72,
   "found": -17,
   "grade": -2.2
  },
  {
   "x": 51.42,
   "z": -61.28,
   "found": -12,
   "grade": 0.0
  },
  {
   "x": 59.39,
   "z": -61.5,
   "found": -14,
   "grade": 0.0
  },
  {
   "x": 65.03,
   "z": -58.55,
   "found": -12,
   "grade": 0.0
  },
  {
   "x": 71.71,
   "z": -56.03,
   "found": -14,
   "grade": 0.0
  },
  {
   "x": 75.86,
   "z": -51.17,
   "found": -14,
   "grade": 0.0
  },
  {
   "x": 83.14,
   "z": -48.0,
   "found": -16,
   "grade": -0.3
  }
 ],
 "halfmoon": {
  "cx": 55.0,
  "cz": 45.0,
  "r": 26.0,
  "a0": -20.0,
  "a1": 100.0,
  "back": 45.0,
  "arc": [
   {
    "x": 79.43,
    "z": 36.11,
    "found": -14
   },
   {
    "x": 80.38,
    "z": 39.37,
    "found": -16
   },
   {
    "x": 80.9,
    "z": 42.73,
    "found": -17
   },
   {
    "x": 80.98,
    "z": 46.13,
    "found": -18
   },
   {
    "x": 80.61,
    "z": 49.51,
    "found": -19
   },
   {
    "x": 79.8,
    "z": 52.82,
    "found": -20
   },
   {
    "x": 78.56,
    "z": 55.99,
    "found": -21
   },
   {
    "x": 76.93,
    "z": 58.97,
    "found": -23
   },
   {
    "x": 74.92,
    "z": 61.71,
    "found": -24
   },
   {
    "x": 72.57,
    "z": 64.17,
    "found": -24
   },
   {
    "x": 69.91,
    "z": 66.3,
    "found": -29
   },
   {
    "x": 67.01,
    "z": 68.06,
    "found": -35
   },
   {
    "x": 63.89,
    "z": 69.43,
    "found": -35
   },
   {
    "x": 60.63,
    "z": 70.38,
    "found": -41
   },
   {
    "x": 57.27,
    "z": 70.9,
    "found": -40
   },
   {
    "x": 53.87,
    "z": 70.98,
    "found": -39
   },
   {
    "x": 50.49,
    "z": 70.61,
    "found": -37
   }
  ],
  "found": -41
 },
 "points": {
  "crown1": {
   "x": 5.0,
   "z": 46.0,
   "y": 0.0
  },
  "crown2": {
   "x": 12.0,
   "z": 55.0,
   "y": 0.0
  },
  "crown3": {
   "x": -2.0,
   "z": 55.0,
   "y": 0.0
  },
  "gun": {
   "x": -52.0,
   "z": -44.0,
   "y": 0.0
  },
  "square": {
   "x": -60.0,
   "z": 22.0,
   "y": 0.0
  },
  "yard": {
   "x": 40.0,
   "z": 5.0,
   "y": 0.0
  }
 }
};
