// Generated by tools/hohensalzburg_plan.py from the survey and the terrain bake.
// Do not edit: change the buildings in the tool and run it again.
export const PLAN = {
 "wings": [
  {
   "name": "Hoher Stock",
   "tag": "hoherstock",
   "kind": "hall",
   "cx": -18.23,
   "cz": -17.17,
   "len": 43.27,
   "wid": 36.99,
   "ry": -1.501,
   "eaves": 25.2,
   "pitch": 34,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Kaplanstöckl",
   "tag": "hoherstock",
   "kind": "hall",
   "cx": 35.84,
   "cz": 0.6,
   "len": 16.75,
   "wid": 11.15,
   "ry": -1.0996,
   "eaves": 16.8,
   "pitch": 45,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Pfisterei",
   "tag": "hoherstock",
   "kind": "hall",
   "cx": 9.41,
   "cz": 0.84,
   "len": 15.52,
   "wid": 11.15,
   "ry": -1.4835,
   "eaves": 12.6,
   "pitch": 45,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Schulhaus",
   "tag": "hoherstock",
   "kind": "hall",
   "cx": 19.96,
   "cz": -9.78,
   "len": 24.27,
   "wid": 7.32,
   "ry": -3.0631,
   "eaves": 12.6,
   "pitch": 45,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Kuchlturm",
   "tag": "hoherstock",
   "kind": "tower",
   "cx": 18.78,
   "cz": 4.61,
   "len": 8.85,
   "wid": 8.85,
   "ry": -0.4625,
   "eaves": 21.0,
   "pitch": 0,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Innere Schloßbastei",
   "tag": "hoherstock",
   "kind": "bastion",
   "cx": -26.62,
   "cz": -0.08,
   "len": 40.61,
   "wid": 35.62,
   "ry": 0.3665,
   "eaves": 8.0,
   "pitch": 0,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "@7,-34",
   "tag": "hoherstock",
   "kind": "hall",
   "cx": 6.55,
   "cz": -33.63,
   "len": 15.7,
   "wid": 14.99,
   "ry": -1.4835,
   "eaves": 12.6,
   "pitch": 45,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Reckturm",
   "tag": "reckturm",
   "kind": "tower",
   "cx": -72.76,
   "cz": -4.99,
   "len": 11.1,
   "wid": 11.1,
   "ry": -0.1047,
   "eaves": 33.0,
   "pitch": 0,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Glockenturm",
   "tag": "reckturm",
   "kind": "tower",
   "cx": -40.19,
   "cz": -33.11,
   "len": 9.8,
   "wid": 9.8,
   "ry": -1.0385,
   "eaves": 25.0,
   "pitch": 0,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Hasengrabenzeughaus",
   "tag": "hasengraben",
   "kind": "hall",
   "cx": -81.63,
   "cz": 19.9,
   "len": 54.61,
   "wid": 21.72,
   "ry": 0.4538,
   "eaves": 14.0,
   "pitch": 45,
   "found": -15,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Salzmagazin",
   "tag": "hasengraben",
   "kind": "hall",
   "cx": -60.7,
   "cz": 8.45,
   "len": 40.62,
   "wid": 9.9,
   "ry": 0.3665,
   "eaves": 10.0,
   "pitch": 45,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Speisehaus",
   "tag": "hasengraben",
   "kind": "hall",
   "cx": -29.98,
   "cz": 34.49,
   "len": 40.67,
   "wid": 10.31,
   "ry": 1.501,
   "eaves": 9.0,
   "pitch": 45,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Hasenturm",
   "tag": "hasengraben",
   "kind": "tower",
   "cx": -53.21,
   "cz": 31.14,
   "len": 8.57,
   "wid": 8.57,
   "ry": 0.2356,
   "eaves": 16.0,
   "pitch": 0,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Schwefelturm",
   "tag": "hasengraben",
   "kind": "round",
   "cx": -62.21,
   "cz": 41.04,
   "len": 6.17,
   "wid": 6.17,
   "ry": -1.9286,
   "eaves": 13.0,
   "pitch": 0,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Arbeitshaus",
   "tag": "arbeitshaus",
   "kind": "hall",
   "cx": 18.42,
   "cz": 34.43,
   "len": 42.3,
   "wid": 16.99,
   "ry": -1.1257,
   "eaves": 12.6,
   "pitch": 45,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Zelt- und Rüstkammer",
   "tag": "arbeitshaus",
   "kind": "hall",
   "cx": 7.68,
   "cz": 30.32,
   "len": 36.94,
   "wid": 7.18,
   "ry": -1.3439,
   "eaves": 8.4,
   "pitch": 45,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Schüttkasten",
   "tag": "arbeitshaus",
   "kind": "hall",
   "cx": 50.33,
   "cz": 16.04,
   "len": 34.61,
   "wid": 15.68,
   "ry": -0.9774,
   "eaves": 12.6,
   "pitch": 45,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Büchsenmacherstöckl",
   "tag": "arbeitshaus",
   "kind": "hall",
   "cx": 70.22,
   "cz": 4.06,
   "len": 12.61,
   "wid": 9.88,
   "ry": -0.8988,
   "eaves": 10.0,
   "pitch": 45,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Geyerturm",
   "tag": "arbeitshaus",
   "kind": "tower",
   "cx": -5.2,
   "cz": 40.77,
   "len": 9.43,
   "wid": 9.43,
   "ry": -1.4835,
   "eaves": 17.0,
   "pitch": 0,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Schmiedturm",
   "tag": "arbeitshaus",
   "kind": "round",
   "cx": 73.73,
   "cz": 6.82,
   "len": 7.04,
   "wid": 7.04,
   "ry": 0.4276,
   "eaves": 14.0,
   "pitch": 0,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Pulverturm",
   "tag": "arbeitshaus",
   "kind": "round",
   "cx": -11.15,
   "cz": 63.2,
   "len": 6.0,
   "wid": 6.0,
   "ry": 1.5533,
   "eaves": 12.0,
   "pitch": 0,
   "found": -31,
   "grade": -5.6,
   "base": 0
  },
  {
   "name": "Großes Zeughaus",
   "tag": "zeughaus",
   "kind": "hall",
   "cx": 92.18,
   "cz": -13.66,
   "len": 45.69,
   "wid": 16.04,
   "ry": -1.0559,
   "eaves": 14.0,
   "pitch": 45,
   "found": -18,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Reißzuggebäude",
   "tag": "zeughaus",
   "kind": "hall",
   "cx": 67.79,
   "cz": -40.0,
   "len": 28.17,
   "wid": 12.17,
   "ry": -1.3003,
   "eaves": 12.6,
   "pitch": 45,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Reißturm",
   "tag": "zeughaus",
   "kind": "tower",
   "cx": 95.6,
   "cz": -32.04,
   "len": 18.03,
   "wid": 18.03,
   "ry": -2.4958,
   "eaves": 18.0,
   "pitch": 0,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Mesner- und Schmiedstöckl",
   "tag": "zeughaus",
   "kind": "hall",
   "cx": 101.64,
   "cz": -51.15,
   "len": 45.8,
   "wid": 8.87,
   "ry": -2.8449,
   "eaves": 10.0,
   "pitch": 45,
   "found": -29,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Altes Zeughaus",
   "tag": "zeughaus",
   "kind": "wall",
   "cx": 114.16,
   "cz": -66.88,
   "len": 37.52,
   "wid": 4.22,
   "ry": -2.8362,
   "eaves": 9.0,
   "pitch": 0,
   "found": -51,
   "grade": -0.2,
   "base": 0
  },
  {
   "name": "Trompeterturm",
   "tag": "zeughaus",
   "kind": "tower",
   "cx": 83.64,
   "cz": -50.96,
   "len": 7.51,
   "wid": 7.51,
   "ry": -1.4835,
   "eaves": 15.0,
   "pitch": 0,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "@120,-36",
   "tag": "zeughaus",
   "kind": "hall",
   "cx": 120.43,
   "cz": -35.68,
   "len": 26.05,
   "wid": 21.8,
   "ry": 0.288,
   "eaves": 10.0,
   "pitch": 45,
   "found": -39,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "@90,-43",
   "tag": "zeughaus",
   "kind": "hall",
   "cx": 90.41,
   "cz": -42.71,
   "len": 14.5,
   "wid": 7.97,
   "ry": -2.2166,
   "eaves": 9.0,
   "pitch": 45,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Georgskirche",
   "tag": "georg",
   "kind": "chapel",
   "cx": 48.15,
   "cz": -36.32,
   "len": 16.93,
   "wid": 8.53,
   "ry": -1.3177,
   "eaves": 10.0,
   "pitch": 55,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Krautturm",
   "tag": "georg",
   "kind": "round",
   "cx": 33.22,
   "cz": -39.16,
   "len": 7.15,
   "wid": 7.15,
   "ry": -1.5446,
   "eaves": 14.0,
   "pitch": 0,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Wachtürmchen der Kuenburgbastei",
   "tag": "georg",
   "kind": "round",
   "cx": 42.59,
   "cz": -51.49,
   "len": 6.0,
   "wid": 6.0,
   "ry": -0.4276,
   "eaves": 10.0,
   "pitch": 0,
   "found": -3,
   "grade": 0.0,
   "base": 0
  },
  {
   "name": "Keutschachbogen",
   "tag": "georg",
   "kind": "gate",
   "cx": 35.23,
   "cz": -65.11,
   "len": 11.94,
   "wid": 9.91,
   "ry": -0.1745,
   "eaves": 9.0,
   "pitch": 45,
   "found": -29,
   "grade": 0.0,
   "base": 0
  }
 ],
 "curtain": [
  {
   "x": 104.0,
   "z": -1.5,
   "found": -12
  },
  {
   "x": 100.27,
   "z": 5.09,
   "found": -16
  },
  {
   "x": 97.1,
   "z": 11.3,
   "found": -14
  },
  {
   "x": 93.54,
   "z": 17.11,
   "found": -16
  },
  {
   "x": 86.27,
   "z": 21.52,
   "found": -15
  },
  {
   "x": 83.05,
   "z": 26.55,
   "found": -16
  },
  {
   "x": 79.08,
   "z": 31.04,
   "found": -25
  },
  {
   "x": 72.22,
   "z": 33.71,
   "found": -25
  },
  {
   "x": 65.36,
   "z": 35.59,
   "found": -18
  },
  {
   "x": 59.8,
   "z": 37.59,
   "found": -21
  },
  {
   "x": 55.03,
   "z": 39.64,
   "found": -27
  },
  {
   "x": 50.24,
   "z": 41.22,
   "found": -21
  },
  {
   "x": 44.48,
   "z": 41.23,
   "found": -17
  },
  {
   "x": 42.02,
   "z": 44.6,
   "found": -22
  },
  {
   "x": 37.87,
   "z": 45.76,
   "found": -22
  },
  {
   "x": 34.5,
   "z": 47.86,
   "found": -22
  },
  {
   "x": 30.99,
   "z": 49.73,
   "found": -21
  },
  {
   "x": 27.35,
   "z": 51.35,
   "found": -21
  },
  {
   "x": 24.08,
   "z": 54.14,
   "found": -23
  },
  {
   "x": 20.03,
   "z": 54.78,
   "found": -20
  },
  {
   "x": 15.9,
   "z": 54.63,
   "found": -18
  },
  {
   "x": 11.91,
   "z": 54.69,
   "found": -17
  },
  {
   "x": 7.95,
   "z": 54.47,
   "found": -15
  },
  {
   "x": 4.05,
   "z": 54.47,
   "found": -15
  },
  {
   "x": -0.27,
   "z": 58.17,
   "found": -23
  },
  {
   "x": -4.51,
   "z": 58.08,
   "found": -22
  },
  {
   "x": -8.88,
   "z": 58.17,
   "found": -20
  },
  {
   "x": -13.47,
   "z": 58.42,
   "found": -19
  },
  {
   "x": -18.16,
   "z": 58.3,
   "found": -15
  },
  {
   "x": -24.91,
   "z": 61.86,
   "found": -20
  },
  {
   "x": -30.5,
   "z": 61.72,
   "found": -18
  },
  {
   "x": -36.78,
   "z": 61.92,
   "found": -17
  },
  {
   "x": -43.56,
   "z": 61.93,
   "found": -18
  },
  {
   "x": -51.21,
   "z": 62.04,
   "found": -21
  },
  {
   "x": -56.22,
   "z": 58.59,
   "found": -17
  },
  {
   "x": -62.18,
   "z": 55.71,
   "found": -16
  },
  {
   "x": -68.83,
   "z": 52.87,
   "found": -16
  },
  {
   "x": -73.72,
   "z": 48.31,
   "found": -14
  },
  {
   "x": -81.41,
   "z": 44.98,
   "found": -15
  },
  {
   "x": -89.92,
   "z": 41.21,
   "found": -20
  },
  {
   "x": -93.61,
   "z": 34.75,
   "found": -13
  },
  {
   "x": -104.06,
   "z": 30.06,
   "found": -15
  },
  {
   "x": -110.89,
   "z": 23.35,
   "found": -16
  },
  {
   "x": -114.32,
   "z": 15.41,
   "found": -15
  },
  {
   "x": -114.71,
   "z": 6.94,
   "found": -13
  },
  {
   "x": -111.0,
   "z": -1.5,
   "found": -11
  },
  {
   "x": -107.22,
   "z": -9.42,
   "found": -16
  },
  {
   "x": -100.45,
   "z": -16.46,
   "found": -17
  },
  {
   "x": -89.86,
   "z": -21.88,
   "found": -17
  },
  {
   "x": -82.92,
   "z": -27.0,
   "found": -16
  },
  {
   "x": -75.28,
   "z": -31.08,
   "found": -22
  },
  {
   "x": -68.0,
   "z": -34.45,
   "found": -22
  },
  {
   "x": -62.43,
   "z": -37.88,
   "found": -22
  },
  {
   "x": -57.6,
   "z": -41.24,
   "found": -25
  },
  {
   "x": -51.44,
   "z": -43.23,
   "found": -18
  },
  {
   "x": -45.32,
   "z": -44.57,
   "found": -20
  },
  {
   "x": -41.12,
   "z": -47.0,
   "found": -26
  },
  {
   "x": -35.82,
   "z": -47.95,
   "found": -23
  },
  {
   "x": -30.32,
   "z": -47.99,
   "found": -20
  },
  {
   "x": -25.31,
   "z": -47.93,
   "found": -18
  },
  {
   "x": -20.75,
   "z": -47.83,
   "found": -17
  },
  {
   "x": -16.58,
   "z": -47.79,
   "found": -17
  },
  {
   "x": -13.48,
   "z": -49.71,
   "found": -26
  },
  {
   "x": -10.07,
   "z": -50.95,
   "found": -23
  },
  {
   "x": -6.34,
   "z": -50.99,
   "found": -21
  },
  {
   "x": -2.77,
   "z": -51.23,
   "found": -18
  },
  {
   "x": 0.41,
   "z": -54.71,
   "found": -24
  },
  {
   "x": 4.15,
   "z": -54.47,
   "found": -20
  },
  {
   "x": 7.97,
   "z": -57.97,
   "found": -24
  },
  {
   "x": 11.96,
   "z": -58.19,
   "found": -16
  },
  {
   "x": 16.59,
   "z": -61.57,
   "found": -21
  },
  {
   "x": 21.0,
   "z": -61.66,
   "found": -18
  },
  {
   "x": 26.7,
   "z": -65.22,
   "found": -22
  },
  {
   "x": 31.85,
   "z": -65.48,
   "found": -19
  },
  {
   "x": 37.12,
   "z": -65.31,
   "found": -18
  },
  {
   "x": 43.0,
   "z": -65.59,
   "found": -16
  },
  {
   "x": 49.06,
   "z": -65.34,
   "found": -15
  },
  {
   "x": 56.18,
   "z": -65.72,
   "found": -14
  },
  {
   "x": 66.89,
   "z": -69.13,
   "found": -20
  },
  {
   "x": 76.14,
   "z": -69.23,
   "found": -19
  },
  {
   "x": 86.82,
   "z": -69.31,
   "found": -20
  },
  {
   "x": 94.59,
   "z": -65.86,
   "found": -15
  },
  {
   "x": 104.37,
   "z": -62.97,
   "found": -14
  },
  {
   "x": 114.16,
   "z": -59.01,
   "found": -18
  },
  {
   "x": 118.37,
   "z": -51.53,
   "found": -14
  },
  {
   "x": 118.29,
   "z": -42.37,
   "found": -11
  },
  {
   "x": 117.99,
   "z": -33.61,
   "found": -13
  },
  {
   "x": 114.57,
   "z": -24.58,
   "found": -13
  },
  {
   "x": 110.97,
   "z": -16.25,
   "found": -12
  },
  {
   "x": 107.25,
   "z": -8.58,
   "found": -12
  }
 ],
 "centre": {
  "x": 6.0,
  "z": -1.5
 },
 "points": {
  "yard1": {
   "x": 34.0,
   "z": -16.0,
   "y": 0.0
  },
  "yard2": {
   "x": -62.0,
   "z": -22.0,
   "y": 0.0
  },
  "yard3": {
   "x": 64.0,
   "z": -55.0,
   "y": 0.0
  },
  "yard4": {
   "x": 7.0,
   "z": 17.0,
   "y": 0.0
  }
 }
};
